import os
import re
import time
import requests

OUTPUT_PATH ="data/tiny_corpus.txt"
TARGET_CHARS = 5_000_000_000
CHUNK_SIZE = 500
SLEEP_BETWEEN = 1.0
MIN_LINE_LEN = 40

TOPICS = [
    # Science (200+)
    "Photosynthesis", "Gravity", "Evolution", "Cell_biology", "Atom", "Electricity", 
    "Magnetism", "Solar_system", "Black_hole", "Climate_change", "Ecosystem", "DNA", 
    "Protein", "Neuroscience", "Quantum_mechanics", "Relativity", "Thermodynamics", 
    "Optics", "Acoustics", "Plate_tectonics", "Volcanic_activity", "Earthquake", 
    "Mineral", "Crystal", "Photon", "Electron", "Neutron", "Proton", "Isotope",
    "Chemical_bond", "Redox_reaction", "Osmosis", "Diffusion", "Enzyme", "Mitochondria",
    "Chloroplast", "Ribosome", "Membrane", "Nucleus", "Chromosome", "Gene", "Mutation",
    "Natural_selection", "Adaptation", "Extinction", "Speciation", "Population_genetics",
    "Ecological_succession", "Food_web", "Predation", "Symbiosis", "Parasitism",
    "Phototropism", "Geotropism", "Homeostasis", "Metabolism", "Photosynthetic_pathway",
    "Glycolysis", "Krebs_cycle", "Electron_transport_chain", "Fermentation", "Aerobic_respiration",
    "Anaerobic_respiration", "ATP", "Photosystem", "Light_reaction", "Dark_reaction",
    "Transcription", "Translation", "mRNA", "tRNA", "rRNA", "Protein_synthesis",
    "DNA_replication", "PCR", "DNA_sequencing", "Genetic_engineering", "CRISPR",
    "Cloning", "Stem_cell", "Differentiation", "Apoptosis", "Cellular_respiration",
    "Fermentation", "Lactate", "Ethanol", "Anaerobic_metabolism", "Catabolism", "Anabolism",
    "Bioenergetics", "Exergonic_reaction", "Endergonic_reaction", "Activation_energy",
    "Enzyme_kinetics", "Substrate_specificity", "Cofactor", "Coenzyme", "Prosthetic_group",
    "Allosteric_regulation", "Feedback_inhibition", "Competitive_inhibition",
    "Non_competitive_inhibition", "Cooperativity", "Immunology", "Antibody", "Antigen",
    "Immune_response", "Vaccination", "Inflammation", "Phagocytosis", "Complement_system",
    "Lymphocyte", "T_cell", "B_cell", "Macrophage", "Cytokine", "Chemokine",
    "Pathogen", "Virus", "Bacterium", "Fungus", "Protozoan", "Prion",
    "Horizontal_gene_transfer", "Conjugation", "Transformation", "Transduction",
    "Plasmid", "Operon", "Promoter", "Enhancer", "Silencer", "TATA_box",
    "Transcription_factor", "RNA_polymerase", "Histone", "Chromatin", "Euchromatin", "Heterochromatin",
    
    # Technology (300+)
    "Artificial_intelligence", "Machine_learning", "Deep_learning", "Neural_network",
    "Computer_vision", "Natural_language_processing", "Reinforcement_learning",
    "Supervised_learning", "Unsupervised_learning", "Transfer_learning", "Convolutional_neural_network",
    "Recurrent_neural_network", "LSTM", "GRU", "Transformer", "Attention_mechanism",
    "Embedding", "Word2vec", "GloVe", "FastText", "BERT", "GPT", "Vision_transformer",
    "Generative_adversarial_network", "Autoencoder", "Variational_autoencoder",
    "Boltzmann_machine", "Restricted_Boltzmann_machine", "Deep_belief_network",
    "Random_forest", "Decision_tree", "Support_vector_machine", "Naive_Bayes",
    "K_nearest_neighbors", "K_means_clustering", "Hierarchical_clustering",
    "DBSCAN", "Gaussian_mixture_model", "Principal_component_analysis",
    "Linear_discriminant_analysis", "T_SNE", "UMAP", "Dimensionality_reduction",
    "Feature_engineering", "Feature_selection", "Normalization", "Standardization",
    "Cross_validation", "Hyperparameter_tuning", "Regularization", "Dropout",
    "Batch_normalization", "Layer_normalization", "Activation_function",
    "ReLU", "Sigmoid", "Tanh", "Softmax", "Loss_function", "Backpropagation",
    "Gradient_descent", "Stochastic_gradient_descent", "Adam", "RMSprop", "Momentum",
    "Computer", "Internet", "Robot", "Smartphone", "Programming_language",
    "Algorithm", "Database", "Cybersecurity", "Virtual_reality", "Augmented_reality",
    "Blockchain", "Cloud_computing", "5G", "6G", "Internet_of_things",
    "Edge_computing", "Fog_computing", "Quantum_computing", "Quantum_bit",
    "Quantum_gate", "Quantum_algorithm", "Quantum_error_correction",
    "Cryptography", "Encryption", "Decryption", "Symmetric_encryption",
    "Asymmetric_encryption", "RSA", "ECC", "AES", "DES", "Hash_function",
    "Digital_signature", "Certificate", "PKI", "Firewall", "Intrusion_detection",
    "Malware", "Virus", "Worm", "Trojan", "Ransomware", "Spyware", "Adware",
    "Phishing", "Social_engineering", "Zero_day", "Vulnerability", "Exploit",
    "Patch", "Update", "Security_audit", "Penetration_testing", "Bug_bounty",
    "Software_engineering", "Agile", "Scrum", "Kanban", "Waterfall",
    "DevOps", "CI_CD", "Docker", "Kubernetes", "Microservices", "Monolith",
    "API", "REST", "SOAP", "GraphQL", "WebSocket", "HTTP", "HTTPS",
    "TCP_IP", "UDP", "DNS", "DHCP", "VPN", "Proxy", "Load_balancer",
    "Cache", "CDN", "Database_optimization", "Query_optimization", "Indexing",
    "Sharding", "Replication", "ACID", "BASE", "NoSQL", "SQL",
    "MongoDB", "PostgreSQL", "MySQL", "Redis", "Elasticsearch", "Cassandra",
    "HBase", "DynamoDB", "BigTable", "Datastore", "Graph_database",
    "Data_warehouse", "Data_lake", "ETL", "Big_data", "Hadoop", "Spark",
    "MapReduce", "HDFS", "Hive", "Pig", "Kafka", "Storm", "Flink",
    "Airflow", "Dbt", "Tableau", "PowerBI", "Looker", "Grafana",
    
    # Geography (500+)
    "United_States", "California", "Texas", "Florida", "New_York", "Illinois",
    "Pennsylvania", "Ohio", "Georgia", "Colorado", "Washington", "Arizona",
    "Massachusetts", "Michigan", "Virginia", "Tennessee", "North_Carolina",
    "Massachusetts", "Connecticut", "Rhode_Island", "New_Hampshire", "Vermont",
    "New_Jersey", "New_Mexico", "Nevada", "Utah", "Oregon", "Wyoming",
    "Montana", "Idaho", "Alaska", "Hawaii", "China", "India", "Russia",
    "Japan", "Germany", "France", "United_Kingdom", "Brazil", "Mexico",
    "Canada", "Australia", "South_Africa", "Egypt", "Nigeria", "Kenya",
    "South_Korea", "Indonesia", "Thailand", "Vietnam", "Philippines", "Malaysia",
    "Singapore", "Hong_Kong", "Taiwan", "Pakistan", "Bangladesh", "Sri_Lanka",
    "Nepal", "Afghanistan", "Iran", "Iraq", "Saudi_Arabia", "Turkey",
    "Israel", "Palestine", "Lebanon", "Jordan", "Syria", "Yemen",
    "United_Arab_Emirates", "Qatar", "Kuwait", "Bahrain", "Oman", "Morocco",
    "Algeria", "Tunisia", "Sudan", "Ethiopia", "Somalia", "Ghana",
    "Ivory_Coast", "Senegal", "Cameroon", "Angola", "Zambia", "Zimbabwe",
    "Botswana", "Namibia", "Mauritius", "Seychelles", "Madagascar", "Mozambique",
    "Poland", "Ukraine", "Romania", "Hungary", "Czech_Republic", "Slovakia",
    "Serbia", "Croatia", "Bosnia", "Montenegro", "Albania", "Macedonia",
    "Bulgaria", "Greece", "Italy", "Spain", "Portugal", "Netherlands",
    "Belgium", "Luxembourg", "Switzerland", "Austria", "Liechtenstein", "Iceland",
    "Norway", "Sweden", "Denmark", "Finland", "Ireland", "Scotland",
    "Wales", "Northern_Ireland", "Chile", "Argentina", "Colombia", "Peru",
    "Ecuador", "Bolivia", "Paraguay", "Uruguay", "Venezuela", "Guyana",
    "Suriname", "French_Guiana", "Panama", "Costa_Rica", "Nicaragua", "Honduras",
    "El_Salvador", "Guatemala", "Belize", "Jamaica", "Haiti", "Dominican_Republic",
    "Cuba", "Puerto_Rico", "Trinidad_Tobago", "Barbados", "Saint_Lucia", "Dominica",
    "Grenada", "Saint_Kitts_Nevis", "Antigua_Barbuda", "Bahamas", "Turks_Caicos",
    "Cayman_Islands", "British_Virgin_Islands", "US_Virgin_Islands", "Puerto_Rico",
    "Antarctica", "Arctic", "Greenland", "Svalbard", "Papua_New_Guinea", "Solomon_Islands",
    "Vanuatu", "Fiji", "Samoa", "Tonga", "Kiribati", "Marshall_Islands",
    "Micronesia", "Palau", "Nauru", "Tuvalu", "Maldives", "Mauritius",
    
    # History (400+)
    "Ancient_Egypt", "Ancient_Greece", "Ancient_Rome", "Ancient_China", "Ancient_India",
    "Byzantine_Empire", "Ottoman_Empire", "Persian_Empire", "Macedonian_Empire",
    "Mongolian_Empire", "Islamic_Golden_Age", "Ming_Dynasty", "Qing_Dynasty",
    "Edo_period", "Meiji_Restoration", "Tokugawa_shogunate", "Samurai",
    "Medieval_Europe", "Medieval_Japan", "Medieval_China", "Medieval_Islam",
    "Dark_Ages", "Middle_Ages", "High_Middle_Ages", "Late_Middle_Ages",
    "Renaissance", "Reformation", "Counter_Reformation", "Enlightenment",
    "Age_of_Exploration", "Colonialism", "Imperialism", "Industrial_Revolution",
    "American_Revolution", "French_Revolution", "Haitian_Revolution", "Latin_American_independence",
    "Napoleonic_Wars", "Crimean_War", "American_Civil_War", "Sino_Japanese_War",
    "Boer_War", "Russo_Japanese_War", "World_War_I", "Roaring_Twenties",
    "Great_Depression", "World_War_II", "Holocaust", "Manhattan_Project",
    "Cold_War", "Korean_War", "Vietnam_War", "Cuban_Missile_Crisis",
    "Space_Race", "Civil_Rights_Movement", "Women_suffrage", "Stonewall_uprising",
    "Fall_of_Berlin_Wall", "Dissolution_of_Soviet_Union", "Gulf_War",
    "Yugoslav_wars", "War_on_Terror", "Iraq_War", "Afghan_War",
    "Arab_Spring", "Brexit", "Trump_presidency", "COVID_19_pandemic",
    
    # Literature (400+)
    "Shakespeare", "Charles_Dickens", "Jane_Austen", "Mark_Twain",
    "Leo_Tolstoy", "Fyodor_Dostoevsky", "Victor_Hugo", "Dante_Alighieri",
    "Homer", "Miguel_Cervantes", "Franz_Kafka", "James_Joyce", "Ernest_Hemingway",
    "F_Scott_Fitzgerald", "Virginia_Woolf", "Gertrude_Stein", "Sylvia_Plath",
    "George_Orwell", "Ray_Bradbury", "Arthur_Clarke", "Isaac_Asimov",
    "J_R_R_Tolkien", "C_S_Lewis", "Stephen_King", "Haruki_Murakami",
    "Gabriel_García_Márquez", "Isabel_Allende", "Toni_Morrison", "Maya_Angelou",
    "Chinua_Achebe", "Salman_Rushdie", "Arundhati_Roy", "Khaled_Hosseini",
    "Poetry", "Novel", "Short_story", "Drama", "Epic", "Sonnet", "Haiku",
    "Limerick", "Ballad", "Tragedy", "Comedy", "Satire", "Allegory",
    "Metaphor", "Simile", "Imagery", "Symbolism", "Foreshadowing", "Irony",
    "Oxymoron", "Personification", "Onomatopoeia", "Alliteration", "Assonance",
    "Consonance", "Free_verse", "Blank_verse", "Iambic_pentameter", "Couplet",
    "Quatrain", "Tercet", "Villanelle", "Sestina", "Rondeau", "Pantoum",
    "Gothic_literature", "Romantic_literature", "Victorian_literature",
    "Modernism", "Postmodernism", "Realism", "Naturalism", "Surrealism",
    "Magical_realism", "Cyberpunk", "Steampunk", "Dystopian", "Utopian",
    "Science_fiction", "Fantasy", "Mystery", "Thriller", "Horror", "Romance",
    "Historical_fiction", "Young_adult", "Children_literature", "Graphic_novel",
    "Autobiography", "Biography", "Memoir", "Essay", "Journalism",
    
    # Arts (300+)
    "Renaissance_art", "Baroque_art", "Rococo_art", "Neoclassical_art",
    "Romantic_art", "Realism_art", "Impressionism", "Post_impressionism",
    "Fauvism", "Expressionism", "Cubism", "Futurism", "Dada", "Surrealism",
    "Abstract_expressionism", "Color_field_painting", "Minimalism", "Pop_art",
    "Conceptual_art", "Performance_art", "Land_art", "Digital_art",
    "Installation_art", "Photography", "Sculpture", "Painting", "Drawing",
    "Printmaking", "Ceramics", "Glass_art", "Jewelry", "Textiles",
    "Leatherwork", "Metalworking", "Woodworking", "Architecture",
    "Neoclassical_architecture", "Gothic_architecture", "Baroque_architecture",
    "Art_deco", "Modernist_architecture", "Postmodern_architecture",
    "Brutalism", "Parametricism", "Biophilic_design", "Sustainable_design",
    "Urban_planning", "Landscape_architecture", "Interior_design",
    "Fashion_design", "Graphic_design", "Web_design", "Game_design",
    
    # Music (300+)
    "Classical_music", "Baroque_music", "Romantic_music", "Modern_classical",
    "Orchestral", "Chamber_music", "Concerto", "Symphony", "Sonata",
    "String_quartet", "Opera", "Ballet", "Musical_theater",
    "Jazz", "Blues", "Rhythm_and_blues", "Soul_music", "Funk",
    "Rock_music", "Hard_rock", "Heavy_metal", "Punk_rock", "Grunge",
    "Alternative_rock", "Indie_rock", "Math_rock", "Progressive_rock",
    "Pop_music", "K_pop", "J_pop", "Bubblegum_pop", "Teen_pop",
    "Electronic_music", "House_music", "Techno", "Trance", "Dubstep",
    "Drum_and_bass", "Ambient_music", "IDM", "Downtempo", "Trip_hop",
    "Hip_hop", "Rap", "Trap_music", "Boom_bap", "Mumble_rap",
    "Country_music", "Bluegrass", "Honky_tonk", "Outlaw_country",
    "Folk_music", "Indie_folk", "Singer_songwriter", "Protest_music",
    "Reggae", "Dancehall", "Ska", "Rocksteady", "Roots_reggae",
    "World_music", "Afrobeat", "Latin_music", "Salsa", "Bachata",
    "Samba", "Bossa_nova", "Merengue", "Cumbia", "Reggaeton",
    "Indian_classical", "Raag", "Carnatic_music", "Hindustani_music",
    "Arabic_music", "Persian_music", "Turkish_music", "Chinese_music",
    "Japanese_music", "Korean_music", "Thai_music", "Indonesian_music",
    
    # Sports (200+)
    "Football", "American_football", "Canadian_football", "Australian_rules_football",
    "Basketball", "Volleyball", "Badminton", "Tennis", "Table_tennis",
    "Squash", "Racquetball", "Pickleball", "Handball", "Ice_hockey",
    "Field_hockey", "Lacrosse", "Cricket", "Baseball", "Softball",
    "Rugby", "American_football", "Gridiron_football", "Aussie_rules",
    "Soccer", "Futsal", "Beach_soccer", "Box_cricket", "Kabaddi",
    "Golf", "Disc_golf", "Archery", "Shooting", "Fencing",
    "Boxing", "Kickboxing", "Muay_Thai", "Wrestling", "Weightlifting",
    "Powerlifting", "Strongman", "Gymnastics", "Rhythmic_gymnastics",
    "Trampoline", "Parkour", "Free_running", "Skateboarding",
    "Snowboarding", "Skiing", "Cross_country_skiing", "Biathlon",
    "Figure_skating", "Speed_skating", "Ice_dancing", "Curling",
    "Swimming", "Diving", "Synchronized_swimming", "Water_polo",
    "Surfing", "Bodyboarding", "Windsurfing", "Kitesurfing",
    "Rowing", "Canoeing", "Kayaking", "Rafting", "Stand_up_paddling",
    "Sailing", "Yachting", "Motorboating", "Jet_skiing", "Wakeboarding",
    "Track_and_field", "Athletics", "Marathon", "Long_distance_running",
    "Sprinting", "Hurdles", "Steeplechase", "Triple_jump", "Long_jump",
    "High_jump", "Pole_vault", "Shot_put", "Discus", "Hammer_throw",
    "Javelin", "Race_walking", "Racewalking", "Decathlon", "Heptathlon",
    "Cycling", "Road_cycling", "Mountain_biking", "Track_cycling",
    "BMX", "Motorcycle_racing", "Formula_One", "Stock_car_racing",
    "Rally_racing", "Drag_racing", "Horse_racing", "Harness_racing",
    "Equestrian", "Show_jumping", "Dressage", "Eventing", "Polo",
    "Extreme_sports", "Climbing", "Sport_climbing", "Mountaineering",
    "Hiking", "Backpacking", "Orienteering", "Geocaching",
    "Bowling", "Ten_pin_bowling", "Duckpin_bowling", "Candlepin_bowling",
    "Darts", "Billiards", "Pool", "Snooker", "Curling", "Shuffleboard",
    "Curling", "Cornhole", "Horseshoes", "Bocce", "Pétanque",
    "Croquet", "Lacrosse", "Hurling", "Camogie", "Australian_football",
    "Gridiron", "Gridiron_football", "Canadian_football",
    
    # Food (200+)
    "Cooking", "Baking", "Cuisine", "Culinary_arts", "Gastronomy",
    "Molecular_gastronomy", "Fusion_cuisine", "Slow_food", "Fast_food",
    "Street_food", "Fine_dining", "Casual_dining", "Fast_casual",
    "Italian_cuisine", "French_cuisine", "Spanish_cuisine", "Portuguese_cuisine",
    "Greek_cuisine", "Turkish_cuisine", "Middle_Eastern_cuisine",
    "Chinese_cuisine", "Japanese_cuisine", "Korean_cuisine", "Vietnamese_cuisine",
    "Thai_cuisine", "Indian_cuisine", "Pakistani_cuisine", "Bangladeshi_cuisine",
    "Mexican_cuisine", "Brazilian_cuisine", "Peruvian_cuisine", "Argentine_cuisine",
    "American_cuisine", "Southern_cuisine", "Soul_food", "Creole_cuisine",
    "Cajun_cuisine", "German_cuisine", "Austrian_cuisine", "Swiss_cuisine",
    "Dutch_cuisine", "Belgian_cuisine", "Scandinavian_cuisine", "Nordic_cuisine",
    "Russian_cuisine", "Polish_cuisine", "Ukrainian_cuisine", "Jewish_cuisine",
    "Vegetarian_cuisine", "Vegan_cuisine", "Raw_food_diet", "Paleo_diet",
    "Ketogenic_diet", "Macrobiotics", "Whole_food", "Organic_food",
    "GMO", "Heirloom", "Local_food", "Farm_to_table", "Slow_food",
    "Wine", "Beer", "Whiskey", "Vodka", "Gin", "Rum", "Tequila",
    "Brandy", "Cognac", "Champagne", "Prosecco", "Cider", "Mead",
    "Coffee", "Tea", "Chocolate", "Espresso", "Cappuccino", "Latte",
    "Bread", "Sourdough", "Baguette", "Croissant", "Bagel", "Pasta",
    "Risotto", "Couscous", "Quinoa", "Rice", "Wheat", "Oats",
    "Noodles", "Ramen", "Udon", "Soba", "Rice_noodles", "Egg_noodles",
    "Vegetable", "Fruit", "Berry", "Nuts", "Seeds", "Legumes",
    "Meat", "Beef", "Pork", "Chicken", "Turkey", "Lamb", "Venison",
    "Fish", "Salmon", "Tuna", "Cod", "Trout", "Sardine", "Anchovy",
    "Shellfish", "Shrimp", "Crab", "Lobster", "Oyster", "Mussel",
    "Clam", "Scallop", "Octopus", "Squid", "Dairy", "Cheese", "Butter",
    "Milk", "Yogurt", "Cream", "Ice_cream", "Spice", "Herb",
    "Garlic", "Onion", "Ginger", "Turmeric", "Cumin", "Coriander",
    "Pepper", "Salt", "Sugar", "Honey", "Maple_syrup", "Molasses",
    "Oil", "Olive_oil", "Coconut_oil", "Sesame_oil", "Vinegar",
    "Sauce", "Condiment", "Dressing", "Dip", "Spread", "Marinade",
    "Soup", "Broth", "Stock", "Stew", "Chili", "Curry", "Gravy",
    "Appetizer", "Entree", "Dessert", "Pastry", "Candy", "Confectionery",
    "Cookie", "Brownie", "Cake", "Pie", "Tart", "Custard", "Pudding",
    "Mousse", "Soufflé", "Meringue", "Jelly", "Jam", "Marmalade",
    "Pickling", "Fermentation", "Canning", "Smoking", "Curing", "Drying",
    "Roasting", "Grilling", "Frying", "Boiling", "Steaming", "Braising",
    "Poaching", "Sautéing", "Stir_frying", "Blending", "Puréeing",
    
    # Philosophy (200+)
    "Philosophy", "Epistemology", "Metaphysics", "Ontology", "Logic",
    "Ethics", "Aesthetics", "Axiology", "Phenomenology", "Existentialism",
    "Pragmatism", "Idealism", "Materialism", "Dualism", "Monism",
    "Nominalism", "Realism", "Constructivism", "Skepticism", "Solipsism",
    "Rationalism", "Empiricism", "Kantian_philosophy", "Hegelian_philosophy",
    "Cartesianism", "Stoicism", "Epicureanism", "Cynicism", "Skepticism",
    "Platonism", "Aristotelianism", "Neoplatonism", "Scholasticism",
    "Thomism", "Occamism", "Nominalism", "Realism", "Moderate_realism",
    "Thomism", "Molinism", "Bañezianism", "Jesuitism", "Probabilism",
    "Casuistry", "Virtue_ethics", "Deontology", "Consequentialism",
    "Utilitarianism", "Rule_utilitarianism", "Act_utilitarianism",
    "Contractarianism", "Social_contract_theory", "Hobbesism", "Lockean",
    "Rousseauism", "Rawlsian", "Nozickian", "Libertarianism",
    "Socialism", "Marxism", "Communism", "Anarchism", "Fascism",
    "Aestheticism", "Functionalism", "Formalism", "Structuralism",
    "Poststructuralism", "Deconstruction", "Phenomenology", "Hermeneutics",
    "Semiotics", "Linguistics_philosophy", "Analytic_philosophy",
    "Continental_philosophy", "Eastern_philosophy", "Western_philosophy",
    "Buddhist_philosophy", "Hindu_philosophy", "Islamic_philosophy",
    "Jewish_philosophy", "Christian_philosophy", "Confucianism", "Taoism",
    "Legalism", "Mohism", "Daodejing", "I_Ching", "Yijing",
    "Sophistry", "Relativism", "Absolutism", "Universalism", "Particularism",
    "Objectivism", "Subjectivism", "Intersubjectivity", "Perspectivism",
    "Determinism", "Indeterminism", "Compatibilism", "Libertarianism",
    "Fatalism", "Free_will", "Agency", "Causality", "Causation",
    "Counterfactuals", "Possible_worlds", "Modal_logic", "Temporal_logic",
    "Identity", "Essence", "Substance", "Property", "Relation",
    "Whole", "Part", "Mereology", "Parthood", "Composition",
    "Time", "Space", "Spacetime", "Eternalism", "Presentism", "Growing_block",
    "Mind", "Consciousness", "Qualia", "Intentionality", "Representation",
    "Sensation", "Perception", "Cognition", "Memory", "Imagination",
    "Emotion", "Desire", "Will", "Intention", "Belief", "Knowledge",
    "Justified_true_belief", "Gettier_problem", "Internalism", "Externalism",
    "Foundationalism", "Coherentism", "Infinitism", "Pragmatism",
    "Truth", "Correspondence_theory", "Coherence_theory", "Pragmatic_theory",
    "Deflationism", "Pluralism", "Realism", "Constructivism", "Relativism",
    "Metaphor", "Analogy", "Symbolism", "Icon", "Index", "Symbol",
    "Meaning", "Reference", "Sense", "Connotation", "Denotation",
    "Extension", "Intension", "Intensionality", "Opacity", "Transparency",
    
    # Psychology (150+)
    "Psychology", "Cognitive_psychology", "Behavioral_psychology",
    "Developmental_psychology", "Social_psychology", "Personality_psychology",
    "Clinical_psychology", "Counseling_psychology", "Educational_psychology",
    "Industrial_organizational_psychology", "Environmental_psychology",
    "Sports_psychology", "Health_psychology", "Forensic_psychology",
    "Military_psychology", "Evolutionary_psychology", "Neuroscience",
    "Neuropsychology", "Psychobiology", "Psychopharmacology",
    "Psychiatry", "Neurology", "Mental_health", "Mental_illness",
    "Anxiety", "Panic_disorder", "Phobia", "OCD", "PTSD", "Depression",
    "Bipolar_disorder", "Schizophrenia", "Autism_spectrum_disorder",
    "ADHD", "Dyslexia", "Dyscalculia", "Apraxia", "Agnosia",
    "Aphasia", "Alexia", "Acalculia", "Prosopagnosia", "Anosognosia",
    "Akinetopsia", "Chromatopsia", "Auditory_processing_disorder",
    "Sensory_processing_disorder", "Eating_disorder", "Anorexia",
    "Bulimia", "Binge_eating", "Substance_use_disorder", "Alcoholism",
    "Gambling_addiction", "Internet_addiction", "Gaming_disorder",
    "Adjustment_disorder", "Stress_response_syndrome", "Acute_stress",
    "Chronic_stress", "Sleep_disorder", "Insomnia", "Narcolepsy",
    "Sleep_apnea", "Restless_leg_syndrome", "Nightmare_disorder",
    "Parasomnias", "Sleepwalking", "Night_terror", "Sexsomnia",
    "Personality_disorder", "Antisocial_personality_disorder",
    "Borderline_personality_disorder", "Narcissistic_personality_disorder",
    "Obsessive_compulsive_personality_disorder", "Paranoid_personality",
    "Schizoid_personality", "Schizotypal_personality", "Histrionic_personality",
    "Dependent_personality", "Avoidant_personality", "Passive_aggressive",
    "Learning", "Memory", "Attention", "Perception", "Sensation",
    "Cognition", "Thinking", "Reasoning", "Problem_solving", "Decision_making",
    "Judgment", "Bias", "Heuristics", "Cognitive_biases", "Confirmation_bias",
    "Availability_heuristic", "Representativeness_heuristic", "Anchoring_bias",
    "Sunk_cost_fallacy", "Gamblers_fallacy", "Hot_hand_fallacy",
    "Illusion", "Hallucination", "Delusion", "Intrusive_thought",
    "Rumination", "Obsession", "Compulsion", "Flashback",
    "Emotion", "Affect", "Mood", "Temperament", "Personality",
    "Trait", "Type", "Big_Five", "MBTI", "Enneagram",
    "Motivation", "Drive", "Incentive", "Goal", "Achievement",
    "Self_actualization", "Self_esteem", "Self_worth", "Self_concept",
    "Identity", "Role", "Status", "Stereotype", "Prejudice",
    "Discrimination", "Bullying", "Aggression", "Violence",
    "Altruism", "Prosocial_behavior", "Empathy", "Sympathy",
    "Attachment", "Bonding", "Love", "Friendship", "Relationship",
    "Group_dynamics", "Conformity", "Obedience", "Compliance",
    "Persuasion", "Influence", "Authority", "Social_proof",
    "Diffusion_of_responsibility", "Bystander_effect", "Deindividuation",
    "Groupthink", "Polarization", "Dehumanization", "Scapegoating",
    "In_group", "Out_group", "In_group_bias", "Out_group_homogeneity",
    "Attribution", "Fundamental_attribution_error", "Actor_observer_bias",
    "Self_serving_bias", "Defensive_attribution", "Just_world_hypothesis",
    "Cognitive_dissonance", "Cognitive_consistency", "Balance_theory",
    
    # Religion (200+)
    "Religion", "Theology", "Comparative_religion", "Religious_studies",
    "Christianity", "Catholicism", "Protestantism", "Orthodoxy",
    "Anglicanism", "Methodism", "Presbyterianism", "Baptism",
    "Pentecostalism", "Mormonism", "Jehovahs_Witnesses", "Seventh_day_adventism",
    "Islam", "Sunni", "Shia", "Sufism", "Wahhabism", "Salafism",
    "Judaism", "Ashkenazi", "Sephardic", "Mizrahi", "Hasidic", "Reform",
    "Conservative", "Orthodox", "Reconstructionist", "Karaite",
    "Buddhism", "Theravada", "Mahayana", "Vajrayana", "Zen", "Pure_Land",
    "Tibetan_Buddhism", "Thai_Buddhism", "Japanese_Buddhism",
    "Hinduism", "Vedanta", "Yoga", "Tantra", "Shaivism", "Vaishnavism",
    "Shaktism", "Smartism", "Karma", "Dharma", "Artha", "Kama", "Moksha",
    "Sikhism", "Sikh_gurus", "Khalsa", "Langar", "Kirtan", "Nam_Japa",
    "Taoism", "Confucianism", "Shinto", "Zoroastrianism", "Baha",
    "Rastafarianism", "Wicca", "Paganism", "Neopaganism", "Druidry",
    "Heathenry", "Ásatrú", "Discordianism", "Satanism", "Theistic_satanism",
    "LaVeyan_satanism", "Church_of_Satan", "Scientology", "New_Age",
    "Spirituality", "Mysticism", "Esotericism", "Occultism", "Magic",
    "Witchcraft", "Sorcery", "Alchemy", "Kabbalah", "Tarot", "Astrology",
    "Numerology", "Reiki", "Chakra", "Aura", "Energy", "Vibration",
    "Spiritualism", "Mediumship", "Channeling", "Past_life_regression",
    "Reincarnation", "Karma", "Samsara", "Nirvana", "Enlightenment",
    "Salvation", "Grace", "Redemption", "Atonement", "Forgiveness",
    "Sin", "Evil", "Good", "Virtue", "Vice", "Morality", "Ethics",
    "Prayer", "Meditation", "Contemplation", "Chanting", "Mantra",
    "Deity", "God", "Goddess", "Pantheon", "Polytheism", "Monotheism",
    "Theism", "Deism", "Atheism", "Agnosticism", "Skepticism",
    "Blasphemy", "Heresy", "Apostasy", "Conversion", "Proselytization",
    "Missionary", "Evangelist", "Pastor", "Priest", "Rabbi", "Imam",
    "Monk", "Nun", "Hermit", "Sage", "Saint", "Martyr", "Prophet",
    "Messiah", "Incarnation", "Avatar", "Bodhisattva", "Arhat",
    "Heaven", "Hell", "Purgatory", "Limbo", "Hades", "Underworld",
    "Paradise", "Garden_of_Eden", "Tower_of_Babel", "Sodom_and_Gomorrah",
    "Ark_of_Covenant", "Holy_Grail", "Sacred_geometry", "Sacred_sites",
    "Pilgrimage", "Crusade", "Jihad", "Holy_war", "Inquisition",
    "Reformation", "Counter_Reformation", "Schism", "Great_Schism",
    "Council", "Synod", "General_council", "Vatican", "Holy_See",
    "Ecumenicism", "Interfaith", "Syncretism", "Religious_tolerance",
    "Religious_intolerance", "Persecution", "Witch_hunt", "Inquisition",
    "Conflict", "Religious_war", "Sectarianism", "Denominationalism",
    
    # Medicine (250+)
    "Medicine", "Surgery", "Anatomy", "Physiology", "Pathology",
    "Pharmacology", "Toxicology", "Immunology", "Microbiology",
    "Epidemiology", "Public_health", "Occupational_medicine", "Tropical_medicine",
    "Internal_medicine", "Family_medicine", "General_practice", "Emergency_medicine",
    "Cardiology", "Thoracic_surgery", "Vascular_surgery", "Cardiac_surgery",
    "Arrhythmia", "Heart_attack", "Stroke", "Hypertension", "Hypotension",
    "Angina", "Myocarditis", "Pericarditis", "Endocarditis", "Valvular_disease",
    "Heart_failure", "Cardiomyopathy", "Congenital_heart_disease",
    "Pulmonology", "Respiratory_medicine", "Pneumology", "Asthma", "COPD",
    "Pneumonia", "Tuberculosis", "Cystic_fibrosis", "Bronchitis", "Emphysema",
    "Pulmonary_fibrosis", "Lung_cancer", "Sleep_apnea", "Pleural_effusion",
    "Gastroenterology", "Hepatology", "Colorectal_surgery", "Gastric_surgery",
    "Esophageal_surgery", "Proctology", "Gastritis", "Peptic_ulcer",
    "Crohn_disease", "Ulcerative_colitis", "Irritable_bowel_syndrome",
    "Celiac_disease", "Diverticulitis", "Appendicitis", "Hemorrhoids",
    "Constipation", "Diarrhea", "Malabsorption", "Fatty_liver_disease",
    "Cirrhosis", "Hepatitis", "Liver_failure", "Gallstones", "Pancreatitis",
    "Endocrinology", "Diabetes", "Thyroid_disorder", "Hyperthyroidism",
    "Hypothyroidism", "Goiter", "Thyroid_cancer", "Parathyroid_disorder",
    "Cushing_syndrome", "Addison_disease", "Pheochromocytoma",
    "Growth_hormone_disorder", "Prolactinoma", "Osteoporosis", "Osteomalacia",
    "Hypogonadism", "Erectile_dysfunction", "Menopause", "Andropause",
    "Infertility", "Polycystic_ovary_syndrome", "Endometriosis",
    "Nephrology", "Urology", "Renal_failure", "Chronic_kidney_disease",
    "Acute_kidney_injury", "Dialysis", "Kidney_transplant", "Nephrotic_syndrome",
    "Nephritis", "Pyelonephritis", "Cystitis", "Urinary_retention",
    "Urinary_incontinence", "Kidney_stone", "Prostate_disease",
    "Benign_prostatic_hyperplasia", "Prostatitis", "Prostate_cancer",
    "Testicular_cancer", "Bladder_cancer", "Renal_cell_carcinoma",
    "Neurology", "Neurosurgery", "Psychiatry", "Psychology",
    "Parkinson_disease", "Alzheimer_disease", "Dementia", "Mild_cognitive_impairment",
    "Amyotrophic_lateral_sclerosis", "Multiple_sclerosis", "Guillain_Barre_syndrome",
    "Myasthenia_gravis", "Muscular_dystrophy", "Spinal_cord_injury",
    "Epilepsy", "Seizure", "Status_epilepticus", "Absence_seizure",
    "Tonic_clonic_seizure", "Partial_seizure", "Febrile_seizure",
    "Migraine", "Tension_headache", "Cluster_headache", "Trigeminal_neuralgia",
    "Vertigo", "Dizziness", "Ataxia", "Tremor", "Dystonia", "Chorea",
    "Paresthesia", "Neuropathy", "Neuropathic_pain", "Phantom_limb_pain",
    "Oncology", "Cancer", "Tumor", "Malignancy", "Metastasis",
    "Chemotherapy", "Radiation_therapy", "Immunotherapy", "Targeted_therapy",
    "Hormone_therapy", "Gene_therapy", "Stem_cell_therapy",
    "Leukemia", "Lymphoma", "Myeloma", "Breast_cancer", "Ovarian_cancer",
    "Endometrial_cancer", "Cervical_cancer", "Pancreatic_cancer",
    "Colorectal_cancer", "Gastric_cancer", "Hepatocellular_carcinoma",
    "Cholangiocarcinoma", "Lung_cancer", "Mesothelioma", "Melanoma",
    "Squamous_cell_carcinoma", "Basal_cell_carcinoma", "Merkel_cell_carcinoma",
    "Dermatology", "Skin_disease", "Acne", "Psoriasis", "Eczema",
    "Dermatitis", "Urticaria", "Angioedema", "Pemphigus", "Bullous_pemphigoid",
    "Vitiligo", "Alopecia", "Hirsutism", "Fungal_infection",
    "Ringworm", "Candida", "Athlete_foot", "Jock_itch", "Nail_fungus",
    "Bacterial_infection", "Impetigo", "Erysipelas", "Cellulitis",
    "Abscess", "Wart", "Molluscum", "Herpes", "Varicella",
    "Wart", "Age_spot", "Hemangioma", "Lipoma", "Cyst",
    "Orthopedics", "Orthopedic_surgery", "Fracture", "Dislocation",
    "Sprain", "Strain", "Osteoarthritis", "Rheumatoid_arthritis",
    "Lupus", "Gout", "Bursitis", "Tendinitis", "Tenosynovitis",
    "Plantar_fasciitis", "Carpal_tunnel_syndrome", "Cubital_tunnel_syndrome",
    "Rotator_cuff_tear", "Meniscus_tear", "ACL_tear", "MCL_tear",
    "Stress_fracture", "Compartment_syndrome", "Rhabdomyolysis",
    "Joint_replacement", "Hip_replacement", "Knee_replacement",
    "Shoulder_surgery", "Back_surgery", "Spinal_fusion",
    "Pediatrics", "Pediatric_surgery", "Neonatology", "Child_health",
    "Infant", "Newborn", "Premature_birth", "Sudden_infant_death_syndrome",
    "Failure_to_thrive", "Cerebral_palsy", "Down_syndrome", "Autism",
    "Dyspraxia", "Dyslexia", "Dyscalculia", "Language_disorder",
    "Speech_disorder", "Cleft_palate", "Congenital_heart_disease",
    "Congenital_anomaly", "Birth_defect", "Genetic_disorder",
    "Immunizations", "Vaccines", "Vaccination", "Immunization_schedule",
    "Gerontology", "Geriatrics", "Aging", "Senescence", "Longevity",
    "Geriatric_syndrome", "Polypharmacy", "Falls", "Incontinence",
    "Delirium", "Dementia", "Frailty", "Sarcopenia",
    "Obstetrics", "Gynecology", "Obstetrics_and_gynecology",
    "Pregnancy", "Prenatal_care", "Labor", "Delivery", "Caesarean_section",
    "Postpartum", "Postpartum_depression", "Gestational_diabetes",
    "Preeclampsia", "Eclampsia", "Placental_abruption", "Placenta_previa",
    "Miscarriage", "Stillbirth", "Ectopic_pregnancy", "Molar_pregnancy",
    "Contraception", "Birth_control", "Condom", "IUD", "Hormonal_contraception",
    "Sterilization", "Tubal_ligation", "Vasectomy", "Assisted_reproduction",
    "Fertility_treatment", "In_vitro_fertilization", "Intrauterine_insemination",
    "Hormone_replacement_therapy", "Menstrual_disorder", "Dysmenorrhea",
    "Amenorrhea", "Oligomenorrhea", "Polymenorrhea", "Menorrhagia",
    "Metrorrhagia", "Sexually_transmitted_infection", "HPV", "Herpes",
    "Chlamydia", "Gonorrhea", "Syphilis", "Trichomoniasis",
    "Bacterial_vaginosis", "Yeast_infection", "Pelvic_inflammatory_disease",
    "Psychiatry", "Mental_health", "Mental_disorder", "Mental_illness",
    "Psychotherapy", "Psychoanalysis", "Cognitive_behavioral_therapy",
    "Dialectical_behavior_therapy", "Acceptance_and_commitment_therapy",
    "Mindfulness_based_cognitive_therapy", "Interpersonal_therapy",
    "Psychopharmacology", "Antidepressant", "Anxiolytic", "Antipsychotic",
    "Mood_stabilizer", "Stimulant", "Hypnotic", "Sedative",
    "Rehabilitation", "Physical_therapy", "Occupational_therapy",
    "Speech_therapy", "Cardiac_rehabilitation", "Pulmonary_rehabilitation",
    # Computer Science & Programming (400+)
    "Data_structure", "Array", "Linked_list", "Stack", "Queue",
    "Tree", "Binary_tree", "Binary_search_tree", "AVL_tree", "Red_black_tree",
    "B_tree", "Trie", "Graph", "Directed_acyclic_graph", "Minimum_spanning_tree",
    "Hash_table", "Heap", "Priority_queue", "Deque", "Set",
    "Sorting_algorithm", "Bubble_sort", "Selection_sort", "Insertion_sort",
    "Merge_sort", "Quick_sort", "Heap_sort", "Counting_sort", "Radix_sort",
    "Bucket_sort", "Shell_sort", "Tim_sort", "Intro_sort",
    "Searching_algorithm", "Linear_search", "Binary_search", "Interpolation_search",
    "Exponential_search", "Jump_search", "Fibonacci_search",
    "Graph_algorithm", "Breadth_first_search", "Depth_first_search",
    "Dijkstra_algorithm", "Bellman_Ford", "Floyd_Warshall", "Prim_algorithm",
    "Kruskal_algorithm", "Topological_sort", "Strongly_connected_components",
    "Dynamic_programming", "Memoization", "Tabulation", "Fibonacci_sequence",
    "Longest_common_subsequence", "Longest_increasing_subsequence",
    "Edit_distance", "Knapsack_problem", "Traveling_salesman_problem",
    "Greedy_algorithm", "Activity_selection", "Huffman_coding",
    "Fractional_knapsack", "Job_sequencing", "Dijkstra_greedy",
    "Divide_and_conquer", "Binary_search_algorithm", "Merge_sort_algorithm",
    "Quick_sort_algorithm", "Strassen_matrix_multiplication",
    "Closest_pair_points", "Karatsuba_multiplication",
    "Backtracking", "N_queens_problem", "Sudoku_solver", "Maze_solver",
    "Permutation", "Combination", "Knight_tour", "Rat_in_maze",
    "Hamiltonian_path", "Coloring_problem",
    "String_algorithm", "Pattern_matching", "String_matching",
    "KMP_algorithm", "Boyer_Moore", "Rabin_Karp", "Z_algorithm",
    "Aho_Corasick", "Manacher_algorithm", "Suffix_array", "Suffix_tree",
    "Trie_algorithm", "Regular_expression", "Palindrome",
    "Cryptographic_algorithm", "RSA_algorithm", "ECC_algorithm",
    "Diffie_Hellman", "Elliptic_curve", "Digital_signature_algorithm",
    "Hashing_algorithm", "MD5", "SHA", "SHA256", "BLAKE2",
    "Bcrypt", "Scrypt", "Argon2",
    "Compression_algorithm", "Huffman_coding_algorithm", "LZ77",
    "LZ78", "DEFLATE", "Burrows_Wheeler_transform", "Run_length_encoding",
    "Arithmetic_coding", "Range_coding",
    "Error_correction_code", "Hamming_code", "Reed_Solomon",
    "Turbo_code", "LDPC_code", "Polar_code",
    "Randomized_algorithm", "Monte_Carlo", "Las_Vegas", "QuickSort_randomized",
    "Randomized_quicksort", "Skip_list", "Bloom_filter",
    "Approximate_algorithm", "Vertex_cover", "Traveling_salesman_approximation",
    "Set_cover", "Bin_packing",
    "Parallel_algorithm", "Parallel_sort", "Parallel_search",
    "Parallel_matrix_multiplication", "Parallel_reduction",
    "Distributed_algorithm", "Consensus_algorithm", "Byzantine_fault_tolerance",
    "Paxos", "Raft", "Two_phase_commit",
    "Quantum_algorithm", "Shor_algorithm", "Grover_algorithm",
    "Variational_quantum_eigensolver", "Quantum_approximate_optimization",
    "Online_algorithm", "Caching_algorithm", "Scheduling_algorithm",
    "Load_balancing", "Resource_allocation",
    "Game_theory", "Nash_equilibrium", "Minimax", "Alpha_beta_pruning",
    "Monte_Carlo_tree_search", "Upper_confidence_bounds",
    "Computational_complexity", "Big_O_notation", "NP_completeness",
    "P_vs_NP", "Turing_machine", "Turing_test",
    "Formal_language", "Regular_language", "Context_free_language",
    "Context_sensitive_language", "Recursive_language",
    "Automata", "Finite_automaton", "Pushdown_automaton",
    "Linear_bounded_automaton", "Turing_machine",
    "Parsing", "Lexical_analysis", "Syntax_analysis", "Semantic_analysis",
    "Compiler", "Interpreter", "Transpiler", "JIT_compiler",
    "Programming_paradigm", "Imperative_programming", "Declarative_programming",
    "Procedural_programming", "Functional_programming", "Object_oriented_programming",
    "Logic_programming", "Constraint_programming", "Aspect_oriented_programming",
    "Generic_programming", "Metaprogramming",
    "Type_system", "Static_typing", "Dynamic_typing", "Gradual_typing",
    "Strong_typing", "Weak_typing", "Type_inference", "Type_checking",
    "Polymorphism", "Parametric_polymorphism", "Ad_hoc_polymorphism",
    "Design_pattern", "Creational_pattern", "Structural_pattern",
    "Behavioral_pattern", "Singleton", "Factory", "Abstract_factory",
    "Builder", "Prototype", "Adapter", "Bridge", "Composite",
    "Decorator", "Facade", "Proxy", "Observer", "Strategy",
    "State", "Template_method", "Command", "Interpreter", "Iterator",
    "Mediator", "Memento", "Chain_of_responsibility", "Visitor",
    
    # Mathematics (500+)
    "Arithmetic", "Addition", "Subtraction", "Multiplication", "Division",
    "Modulo", "Exponentiation", "Root", "Logarithm", "Prime_number",
    "Composite_number", "Perfect_number", "Fibonacci_number", "Factorial",
    "Permutation_mathematics", "Combination_mathematics", "Binomial_coefficient",
    "Number_theory", "Divisibility", "Greatest_common_divisor", "Least_common_multiple",
    "Euclidean_algorithm", "Diophantine_equation", "Modular_arithmetic",
    "Chinese_remainder_theorem", "Fermat_little_theorem", "Euler_theorem",
    "Quadratic_residue", "Legendre_symbol", "Jacobi_symbol",
    "Integer_factorization", "Trial_division", "Pollard_rho",
    "Quadratic_sieve", "General_number_field_sieve",
    "Algebra", "Variable", "Expression", "Equation", "Inequality",
    "Linear_equation", "Quadratic_equation", "Cubic_equation", "Polynomial",
    "Rational_expression", "Radical_expression", "Absolute_value",
    "Linear_inequality", "System_of_equations", "Matrix", "Determinant",
    "Inverse_matrix", "Eigenvalue", "Eigenvector", "Diagonalization",
    "Vector", "Vector_addition", "Scalar_multiplication", "Dot_product",
    "Cross_product", "Vector_space", "Linear_independence", "Span",
    "Basis", "Dimension", "Norm", "Orthogonality", "Gram_Schmidt",
    "Geometry", "Point", "Line", "Plane", "Angle", "Triangle",
    "Circle", "Ellipse", "Parabola", "Hyperbola", "Polygon",
    "Polyhedron", "Sphere", "Cone", "Cylinder", "Cube",
    "Euclidean_geometry", "Non_euclidean_geometry", "Riemannian_geometry",
    "Hyperbolic_geometry", "Spherical_geometry", "Projective_geometry",
    "Affine_geometry", "Coordinate_geometry", "Analytic_geometry",
    "Trigonometry", "Sine", "Cosine", "Tangent", "Cotangent",
    "Secant_trigonometry", "Cosecant", "Inverse_trigonometric",
    "Trigonometric_identity", "Law_of_sines", "Law_of_cosines",
    "Half_angle_formula", "Double_angle_formula", "Sum_to_product",
    "Calculus", "Limit", "Continuity", "Derivative", "Integral",
    "Differential_equation", "Partial_derivative", "Gradient",
    "Divergence", "Curl", "Laplacian", "Line_integral", "Surface_integral",
    "Volume_integral", "Green_theorem", "Stokes_theorem", "Divergence_theorem",
    "Fundamental_theorem_of_calculus", "Mean_value_theorem",
    "Rolle_theorem", "Taylor_series", "Fourier_series", "Power_series",
    "Convergence", "Absolute_convergence", "Conditional_convergence",
    "Series_convergence_test", "Ratio_test", "Root_test", "Integral_test",
    "Comparison_test", "Limit_comparison_test",
    "Multivariable_calculus", "Partial_differentiation", "Multiple_integration",
    "Change_of_variables", "Jacobian", "Vector_calculus",
    "Real_analysis", "Set_theory", "Topology", "Metric_space",
    "Compact_space", "Connected_space", "Hausdorff_space", "Complete_metric_space",
    "Banach_space", "Hilbert_space", "Function_space", "Measure_theory",
    "Lebesgue_integral", "Borel_measure", "Probability_measure",
    "Complex_analysis", "Complex_number", "Holomorphic_function",
    "Cauchy_integral_theorem", "Residue_theorem", "Conformal_mapping",
    "Riemann_surface", "Analytic_continuation",
    "Functional_analysis", "Linear_operator", "Bounded_operator",
    "Self_adjoint_operator", "Spectrum", "Spectral_theorem",
    "Operator_norm", "Weak_convergence", "Strong_convergence",
    "Differential_geometry", "Manifold", "Tangent_space", "Cotangent_space",
    "Differential_form", "Exterior_derivative", "De_Rham_cohomology",
    "Riemannian_metric", "Geodesic", "Curvature", "Torsion",
    "Connection", "Parallel_transport", "Holonomy",
    "Algebraic_geometry", "Variety", "Algebraic_curve", "Algebraic_surface",
    "Scheme", "Sheaf", "Cohomology", "Intersection_theory",
    "Number_theory_advanced", "Galois_theory", "Algebraic_number",
    "Algebraic_integer", "Ring_of_integers", "Ideal", "Prime_ideal",
    "Factorization", "Unique_factorization_domain", "Principal_ideal_domain",
    "Abstract_algebra", "Group", "Ring", "Field", "Module",
    "Group_theory", "Subgroup", "Normal_subgroup", "Quotient_group",
    "Homomorphism", "Isomorphism", "Automorphism", "Direct_product",
    "Semi_direct_product", "Free_group", "Abelian_group", "Cyclic_group",
    "Symmetric_group", "Alternating_group", "Dihedral_group",
    "Quaternion_group", "Simple_group", "Composition_series",
    "Ring_theory", "Subring", "Ideal_ring", "Principal_ideal",
    "Prime_ideal", "Maximal_ideal", "Quotient_ring", "Integral_domain",
    "Unique_factorization_domain", "Euclidean_domain", "Principal_ideal_domain",
    "Field_theory", "Extension_field", "Algebraic_extension",
    "Transcendental_extension", "Separable_extension", "Normal_extension",
    "Galois_extension", "Splitting_field",
    "Linear_algebra", "Vector_space", "Subspace", "Linear_transformation",
    "Rank", "Nullity", "Row_space", "Column_space", "Null_space",
    "Orthogonal_complement", "Projection", "Least_squares",
    "QR_decomposition", "Singular_value_decomposition", "Cholesky_decomposition",
    "Statistics", "Descriptive_statistics", "Inferential_statistics",
    "Mean", "Median", "Mode", "Standard_deviation", "Variance",
    "Covariance", "Correlation", "Probability_distribution",
    "Normal_distribution", "Binomial_distribution", "Poisson_distribution",
    "Uniform_distribution", "Exponential_distribution", "Chi_squared_distribution",
    "T_distribution", "F_distribution", "Hypothesis_testing",
    "P_value", "Confidence_interval", "Regression_analysis",
    "Linear_regression", "Logistic_regression", "Polynomial_regression",
    "Multiple_regression", "Time_series", "ARIMA", "Exponential_smoothing",
    "Bayesian_statistics", "Prior", "Posterior", "Likelihood",
    "Bayes_theorem", "Bayesian_inference", "Markov_chain_Monte_Carlo",
    "Variational_inference", "Expectation_maximization",
    "Probability_theory", "Sample_space", "Event", "Conditional_probability",
    "Independence", "Bayes_rule", "Law_of_total_probability",
    "Random_variable", "Probability_mass_function", "Probability_density_function",
    "Cumulative_distribution_function", "Expected_value", "Moment",
    "Characteristic_function", "Moment_generating_function",
    "Limit_theorems", "Law_of_large_numbers", "Central_limit_theorem",
    "Convergence_types", "Almost_sure_convergence", "Convergence_in_probability",
    "Convergence_in_distribution", "Convergence_in_mean",
    "Stochastic_process", "Markov_process", "Wiener_process",
    "Brownian_motion", "Poisson_process", "Martingale",
    "Submartingale", "Supermartingale", "Optional_stopping_theorem",
    "Discrete_mathematics", "Propositional_logic", "First_order_logic",
    "Mathematical_induction", "Strong_induction", "Well_ordering_principle",
    "Recursive_definition", "Recursive_algorithm", "Recursion_relation",
    "Combinatorics", "Permutation_combinatorics", "Combination_combinatorics",
    "Stirling_number", "Catalan_number", "Bell_number",
    "Partition_integer", "Young_diagram", "Generating_function",
    "Inclusion_exclusion_principle", "Pigeonhole_principle",
    "Graph_theory", "Vertex", "Edge", "Path", "Cycle",
    "Connected_graph", "Disconnected_graph", "Acyclic_graph",
    "Tree_graph", "Forest", "Spanning_tree", "Minimum_spanning_tree",
    "Bipartite_graph", "Complete_graph", "Planar_graph", "Chromatic_number",
    "Clique", "Independent_set", "Vertex_cover", "Matching",
    "Hall_marriage_theorem", "König_theorem", "Network_flow",
    "Max_flow_min_cut", "Ford_Fulkerson", "Edmonds_Karp",
    "Game_theory_advanced", "Cooperative_game", "Non_cooperative_game",
    "Symmetric_game", "Zero_sum_game", "Simultaneous_game",
    "Sequential_game", "Information_set", "Perfect_information",
    "Imperfect_information", "Mixed_strategy", "Pure_strategy",
    "Dominant_strategy", "Dominated_strategy", "Pareto_efficiency",
    "Prisoner_dilemma", "Coordination_game", "Chicken_game",
    "Stag_hunt", "Matching_pennies", "Rock_paper_scissors",
    "Auction_theory", "Mechanism_design", "Voting_theory",
    "Social_choice", "Arrow_impossibility_theorem",
    
    # More Fields
    "Astronomy", "Cosmology", "Astrophysics", "Exoplanet", "Pulsar",
    "Quasar", "Active_galactic_nucleus", "Neutron_star", "White_dwarf",
    "Red_dwarf", "Red_giant", "Supergiant", "Hypergiant", "Herbig_Haro",
    "T_Tauri_star", "Main_sequence", "Hertzsprung_Russell_diagram",
    "Stellar_evolution", "Nucleosynthesis", "Supernova", "Type_Ia",
    "Type_II", "Hypernova", "Kilonova", "Gravitational_wave",
    "Planetary_science", "Planetary_geology", "Astrobiology",
    "Exoplanetology", "Hot_Jupiter", "Super_Earth", "Mini_Neptune",
    "Terrestrial_planet", "Gas_giant", "Ice_giant",
    "Habitability", "Circumstellar_habitable_zone", "Drake_equation",
    "Fermi_paradox", "Great_filter", "Panspermia",
    "Atmospheric_science", "Troposphere", "Stratosphere", "Mesosphere",
    "Thermosphere", "Exosphere", "Weather_system", "Hurricane",
    "Tornado", "Lightning", "Thunder", "Hail", "Snow", "Rain",
    "Cloud_formation", "Precipitation", "Hydrological_cycle",
    "Oceanography", "Marine_biology", "Coral_reef", "Kelp_forest",
    "Deep_sea_vent", "Bioluminescence", "Chemosynthesis", "Symbiosis",
    "Marine_ecosystem", "Ocean_acidification", "Eutrophication",
    "Biogeography", "Biogeographic_realm", "Biome", "Savanna",
    "Grassland", "Tundra", "Boreal_forest", "Temperate_forest",
    "Rainforest", "Tropical_rainforest", "Mangrove", "Wetland",
    "Aquatic_ecosystem", "Freshwater_ecosystem", "Marine_ecosystem",
    "Terrestrial_ecosystem", "Desert_ecosystem", "Alpine_ecosystem",
    "Symbiosis_advanced", "Mutualism", "Commensalism", "Parasitism",
    "Predation", "Competition", "Niche", "Habitat", "Range",
    "Population_ecology", "Population_dynamics", "Carrying_capacity",
    "Logistic_growth", "Exponential_growth", "Population_regulation",
    "Density_dependent", "Density_independent", "Metapopulation",
    "Source_sink_dynamics", "Conservation_biology", "Endangered_species",
    "Extinction", "Biodiversity_loss", "Habitat_fragmentation",
    "Habitat_restoration", "Species_reintroduction",
    "Evolutionary_biology", "Natural_selection", "Artificial_selection",
    "Sexual_selection", "Kin_selection", "Inclusive_fitness",
    "Evolutionary_game_theory", "Red_queen_hypothesis",
    "Evolutionary_stable_strategy", "Coevolution", "Convergent_evolution",
    "Divergent_evolution", "Parallel_evolution", "Evolutionary_arms_race",
    "Molecular_evolution", "Molecular_clock", "DNA_sequencing",
    "Phylogenetics", "Cladistics", "Phylogenetic_tree", "Evolutionary_tree",
    
    # Additional specialized domains
    "Nanotechnology", "Nanoparticle", "Nanomaterial", "Nanotube",
    "Fullerene", "Graphene", "Nanoelectronics", "Nanophotonics",
    "Nanorobotics", "Nanomedicine", "Drug_delivery", "Biosensor",
    "Biotechnology", "Genetic_engineering", "Synthetic_biology",
    "Metabolic_engineering", "Fermentation", "Biofuel", "Biomaterial",
    "Tissue_engineering", "Regenerative_medicine", "Organ_transplantation",
    "Xenotransplantation", "Gene_therapy", "Cell_therapy",
    "Immunotherapy", "CAR_T_cell_therapy", "Checkpoint_inhibitor",
    "Personalized_medicine", "Pharmacogenomics", "Precision_medicine",
    "Omics", "Genomics", "Proteomics", "Metabolomics", "Lipidomics",
    "Transcriptomics", "Microbiomics", "Bioinformatics",
    "Computational_biology", "Systems_biology", "Network_biology",
    "Synthetic_biology", "Biochemistry", "Biochemical_pathway",
    "Enzyme_mechanism", "Protein_folding", "Protein_structure",
    "Protein_interaction", "Signal_transduction", "Cell_cycle",
    "Apoptosis", "Autophagy", "Senescence", "Necrosis",
    "Inflammation", "Immune_response", "Innate_immunity",
    "Adaptive_immunity", "Humoral_immunity", "Cell_mediated_immunity",
    "Allergic_reaction", "Autoimmune_disease", "Immunodeficiency",
    "Toxicology", "Environmental_toxicology", "Ecotoxicology",
    "Industrial_toxicology", "Food_toxicology", "Drug_toxicity",
    "Pharmacokinetics", "Pharmacodynamics", "Metabolism",
    "Absorption", "Distribution", "Elimination", "Clearance",
    "Half_life", "Bioavailability", "Bioequivalence", "Drug_interaction",

    # Biology & Life Sciences (300+)
    "Mitochondrial_DNA", "Chloroplast_DNA", "Plasmid", "Episome",
    "Transposon", "Retrotransposon", "LINE_element", "SINE_element",
    "DNA_methylation", "Histone_modification", "Epigenetics", "Gene_expression",
    "Transcriptional_regulation", "Post_transcriptional_regulation",
    "Translational_regulation", "Post_translational_modification",
    "Phosphorylation", "Ubiquitination", "Acetylation", "Sumoylation",
    "Glycosylation", "Lipidation", "Proteolysis", "Protein_cleavage",
    "Signal_peptide", "Nuclear_localization_signal", "Transmembrane_domain",
    "Protein_domain", "Conserved_domain", "Functional_domain",
    "Protein_family", "Ortholog", "Paralog", "Homolog", "Sequence_alignment",
    "Multiple_sequence_alignment", "Phylogenetic_profiling", "Orthology_inference",
    "Cellular_compartment", "Nucleus", "Nucleolus", "Nuclear_membrane",
    "Endoplasmic_reticulum", "Golgi_apparatus", "Lysosome", "Peroxisome",
    "Mitochondrion", "Chloroplast", "Ribosome", "Proteasome",
    "Spliceosome", "Nucleosome", "Centrosome", "Centriole", "Flagellum",
    "Cilium", "Cell_membrane", "Plasma_membrane", "Phospholipid",
    "Lipid_raft", "Caveolin", "Ion_channel", "Aquaporin",
    "Transporter", "Active_transport", "Passive_transport", "Endocytosis",
    "Exocytosis", "Phagocytosis", "Pinocytosis", "Receptor_mediated_endocytosis",
    "Vesicular_transport", "SNARE_complex", "v_SNARE", "t_SNARE",
    "Tethering_complex", "Coat_protein", "COPII", "COPI", "Clathrin",
    "Adaptor_protein", "Cargo_protein", "Retrieval_signal", "Sorting_signal",
    "ER_retention_signal", "ER_export_signal", "Secretory_signal",
    "Mitochondrial_targeting_signal", "Chloroplast_targeting_signal",
    "Peroxisomal_targeting_signal", "Nuclear_targeting_signal",
    "Protein_trafficking", "Protein_sorting", "Protein_targeting",
    "Unfolded_protein_response", "ER_stress", "Chaperone", "Heat_shock_protein",
    "Chaperonin", "Protein_aggregation", "Amyloid", "Prion_protein",
    "Cell_death", "Apoptosis", "Necrosis", "Autophagy", "Senescence",
    "Programmed_cell_death", "Intrinsic_pathway", "Extrinsic_pathway",
    "Bcl_2_family", "Death_receptor", "Caspase", "Apoptosome",
    "Mitochondrial_outer_membrane_permeabilization", "Cytochrome_c_release",
    "Metabolic_pathway", "Glycolysis", "Gluconeogenesis", "Glycogenesis",
    "Glycogenolysis", "Pentose_phosphate_pathway", "Citric_acid_cycle",
    "Electron_transport_chain", "Oxidative_phosphorylation",
    "Fatty_acid_oxidation", "Fatty_acid_synthesis", "Ketogenesis",
    "Amino_acid_metabolism", "Urea_cycle", "Nucleotide_metabolism",
    "Purine_metabolism", "Pyrimidine_metabolism", "Cholesterol_metabolism",
    "Steroid_hormone_synthesis", "Eicosanoid_metabolism",
    "Detoxification", "Phase_I_metabolism", "Phase_II_metabolism",
    "Phase_III_metabolism", "Cytochrome_P450", "Glutathione_S_transferase",
    "UDP_glucuronosyltransferase", "Acetyl_CoA", "Adenosine_triphosphate",
    "GTP", "Creatine_phosphate", "NADH", "FADH2", "Electron_carrier",
    "Energy_metabolism", "Basal_metabolic_rate", "Thermic_effect",
    "Exercise_induced_thermogenesis", "Non_exercise_activity_thermogenesis",
    
    # Genetics (200+)
    "Genetic_code", "Codon", "Anticodon", "Start_codon", "Stop_codon",
    "Wobble_base_pairing", "Genetic_variation", "Single_nucleotide_polymorphism",
    "Insertion_deletion", "Copy_number_variation", "Structural_variation",
    "Chromosomal_rearrangement", "Inversion", "Translocation", "Deletion",
    "Duplication", "Aneuploidy", "Polyploidy", "Triploidy", "Tetraploidy",
    "Gene_dosage", "Gene_expression_dosage", "X_inactivation", "Genomic_imprinting",
    "Epigenetic_inheritance", "Transgenerational_epigenetic_inheritance",
    "DNA_methylation_pattern", "Histone_code", "Chromatin_remodeling",
    "Nucleosome_positioning", "Chromatin_accessibility", "Open_chromatin",
    "Closed_chromatin", "Heterochromatin_spreading", "Euchromatin_domain",
    "Locus_control_region", "Enhancer_element", "Silencer_element",
    "Insulator_element", "Matrix_attachment_region", "Scaffold_attachment_region",
    "Transcription_factor_binding_site", "Cis_regulatory_element",
    "Trans_acting_factor", "Promoter_proximal_element", "Proximal_promoter",
    "Distal_promoter", "TATA_box_sequence", "GC_box", "CAAT_box",
    "Kozak_consensus", "Ribosome_binding_site", "Shine_Dalgarno_sequence",
    "Poly_adenylation_signal", "Cleavage_polyadenylation_specificity_factor",
    "Splicing_signal", "Splice_site", "Branch_point", "Pyrimidine_tract",
    "Intron_sequence", "Exon_sequence", "Constitutive_exon", "Alternative_exon",
    "Exon_skipping", "Alternative_splicing", "Alternative_promoter",
    "Alternative_polyadenylation", "Alternative_transcription_initiation",
    "Alternative_transcription_termination", "Trans_splicing",
    "RNA_editing", "A_to_I_editing", "C_to_U_editing",
    "Genome_size", "C_value", "C_value_paradox", "Haploid_genome",
    "Diploid_genome", "Polyploid_genome", "Pangenome", "Accessory_genome",
    "Core_genome", "Synteny", "Genome_collinearity", "Breakpoint_region",
    "Orthologous_region", "Paralogous_region", "Segmental_duplication",
    "Tandem_duplication", "Interspersed_duplication",
    "Recombination_hotspot", "Recombination_coldspot", "Crossover",
    "Non_allelic_homologous_recombination", "Non_homologous_end_joining",
    "Homology_directed_repair", "Mismatch_repair", "Base_excision_repair",
    "Nucleotide_excision_repair", "Translesion_synthesis",
    "DNA_damage", "UV_damage", "Oxidative_damage", "Alkylation_damage",
    "Cross_linking_damage", "Double_strand_break", "Single_strand_break",
    "Abasic_site", "Thymine_dimer", "6_4_photoproduct",
    
    # Molecular Biology (200+)
    "RNA_processing", "5_prime_capping", "3_prime_polyadenylation",
    "RNA_splicing", "Self_splicing_intron", "Group_I_intron", "Group_II_intron",
    "Small_nuclear_RNA", "Small_nucleolar_RNA", "MicroRNA", "Long_noncoding_RNA",
    "Small_interfering_RNA", "PIWI_interacting_RNA", "Circular_RNA",
    "RNA_virus", "Retrovirus", "Reverse_transcriptase", "Integrase",
    "Protease", "Envelope_protein", "Capsid_protein", "Matrix_protein",
    "Host_cell_receptor", "Viral_entry", "Cell_to_cell_transmission",
    "Latency", "Lytic_cycle", "Lysogenic_cycle", "Temperate_phage",
    "Lytic_phage", "Bacteriophage", "T4_phage", "Lambda_phage",
    "Bacterial_conjugation", "Pilus", "F_plasmid", "Transfer_RNA",
    "tRNA_modification", "Pseudouridine", "Inosine", "Queuosine",
    "Ribosomal_RNA", "rRNA_processing", "rRNA_modification",
    "Ribosome_biogenesis", "Ribosomal_protein", "Ribosomal_RNA",
    "Large_subunit", "Small_subunit", "Peptidyl_site", "Aminoacyl_site",
    "Exit_site", "Decoding_center", "Peptidyl_transferase_center",
    "GTPase_associated_center", "Elongation_factor", "Release_factor",
    "Stop_codon_readthrough", "Suppressor_mutation", "Wobble_mutation",
    "Translation_initiation", "Translation_elongation", "Translation_termination",
    "Ribosomal_frameshifting", "Internal_ribosome_entry_site",
    "5_prime_UTR", "3_prime_UTR", "Kozak_sequence", "Codon_usage_bias",
    "Gene_expression_regulation", "Transcriptional_control", "Epigenetic_control",
    "Chromatin_based_control", "Histone_acetylation", "Histone_deacetylation",
    "Histone_methylation", "Histone_demethylation", "Histone_phosphorylation",
    "Histone_ubiquitination", "Histone_sumoylation", "Histone_variants",
    "H1_linker_histone", "H2A_variant", "H2B_variant", "H3_variant", "H4_variant",
    "Core_histone", "Nucleosomal_DNA", "Linker_DNA", "Nucleosome_core_particle",
    "Nucleosome_assembly", "Chromatin_assembly_factor", "Histone_chaperone",
    "Nucleosome_remodeling", "SWI_SNF_complex", "ISWI_complex", "CHD_complex",
    "INO80_complex", "Chromatin_remodeling_enzyme", "ATPase",
    "Histone_deacetylase", "HDAC_complex", "Co_repressor_complex",
    "Co_activator_complex", "Mediator_complex", "Transcription_factor_complex",
    "Enhanceosome", "Preinitiation_complex", "Pre_IC", "Transcription_bubble",
    "RNA_polymerase_II", "RNA_polymerase_I", "RNA_polymerase_III",
    "Mitochondrial_RNA_polymerase", "Chloroplast_RNA_polymerase",
    "Sigma_factor", "Promoter_specificity", "Promoter_selectivity",
    "Initiation_factor", "IF1", "IF2", "IF3", "eIF1", "eIF2", "eIF3",
    "eIF4", "eIF5", "eIF6", "eIF7", "eIF8", "eIF9", "eIF10",
    "CAP_binding_protein", "PABP_binding_protein", "Ribosomal_scanning",
    "START_codon_recognition", "Ribosomal_positioning",
    
    # Ecology & Evolution (250+)
    "Niche_differentiation", "Niche_partitioning", "Resource_partitioning",
    "Competitive_exclusion_principle", "Gause_principle", "Competitive_release",
    "Apparent_competition", "Indirect_competition", "Exploitative_competition",
    "Interference_competition", "Dominance_hierarchy", "Pecking_order",
    "Territoriality", "Foraging_behavior", "Optimal_foraging_theory",
    "Marginal_value_theorem", "Prey_choice", "Patch_use", "Time_allocation",
    "Reproductive_strategy", "r_selection", "K_selection", "Bet_hedging",
    "Life_history_evolution", "Trade_off", "Senescence", "Antagonistic_pleiotropy",
    "Disposable_soma_theory", "Evolutionary_constraint", "Pleiotropic_constraint",
    "Genetic_constraint", "Developmental_constraint", "Phylogenetic_constraint",
    "Developmental_canalization", "Genetic_assimilation", "Evolvability",
    "Evolutionary_potential", "Mutational_target", "Genetic_load",
    "Mutation_load", "Inbreeding_depression", "Heterosis", "Outbreeding_depression",
    "Genetic_drift", "Founder_effect", "Bottleneck", "Coalescence",
    "Effective_population_size", "Census_population_size", "Genetic_variance",
    "Heritability", "Broad_sense_heritability", "Narrow_sense_heritability",
    "Environmental_variance", "Phenotypic_variance", "Genotypic_variance",
    "Additive_genetic_variance", "Dominance_variance", "Epistatic_variance",
    "Linkage_disequilibrium", "Haplotype_block", "Genome_wide_association",
    "Quantitative_trait_locus", "Marker_assisted_selection", "Genomic_selection",
    "Quantitative_genetics", "Polygenic_inheritance", "Oligogenic_inheritance",
    "Monogenic_inheritance", "Maternal_effect", "Paternal_effect",
    "Cytoplasmic_inheritance", "Maternal_inheritance", "Uniparental_inheritance",
    "Sex_linked_inheritance", "X_linkage", "Y_linkage", "Sex_influenced_trait",
    "Sex_limited_trait", "Lethal_allele", "Conditional_lethal", "Temperature_sensitive",
    "Evolutionary_arms_race", "Predator_prey_dynamics", "Coevolutionary_cycle",
    "Mutualistic_coevolution", "Antagonistic_coevolution", "Diffuse_coevolution",
    "Pairwise_coevolution", "Reciprocal_coevolution", "Escape_and_radiate",
    "Red_queen_hypothesis", "Red_queen_dynamics", "Evolutionary_rescue",
    "Purifying_selection", "Disruptive_selection", "Balancing_selection",
    "Frequency_dependent_selection", "Negative_frequency_dependent_selection",
    "Positive_frequency_dependent_selection", "Heterozygote_advantage",
    "Overdominance", "Underdominance", "Metapopulation_genetics",
    "Evolutionary_stability", "Evolutionary_strategy", "Polymorphism",
    "Balanced_polymorphism", "Transient_polymorphism", "Allele_frequency_change",
    "Fixation", "Loss", "Substitution", "Mutation_substitution_balance",
    "Selection_mutation_balance", "Migration_selection_balance",
    "Phylogeography", "Phylogeographic_structure", "Geographic_isolation",
    "Reproductive_isolation", "Behavioral_isolation", "Temporal_isolation",
    "Mechanical_isolation", "Gametic_isolation", "Prezygotic_barrier",
    "Postzygotic_barrier", "Hybrid_zone", "Secondary_contact", "Sympatric_speciation",
    "Parapatric_speciation", "Peripatric_speciation", "Allopatric_speciation",
    "Microallopatry", "Macroallopatry", "Phylopatry", "Philopatry",
    "Dispersal", "Colonization", "Range_expansion", "Range_contraction",
    "Invasive_species", "Biological_invasion", "Invasion_biology",
    "Enemy_release_hypothesis", "Evolution_of_invasiveness",
    "Adaptive_radiation", "Explosive_diversification", "Key_innovation",
    "Niche_construction", "Ecosystem_engineering", "Genetic_engineering_ecology",
    
    # Environmental Science (150+)
    "Air_quality", "Air_pollution", "Particulate_matter", "Ozone",
    "Nitrogen_oxide", "Sulfur_dioxide", "Carbon_monoxide", "Volatile_organic_compound",
    "Acid_rain", "Photochemical_smog", "Indoor_air_quality", "Sick_building_syndrome",
    "Radon", "Asbestos", "Lead_poisoning", "Mercury_contamination",
    "Persistence_organic_pollutant", "PCB", "Dioxin", "Pesticide",
    "Water_quality", "Water_pollution", "Eutrophication", "Dead_zone",
    "Hypoxia", "Anoxia", "Acidification", "Salinization", "Contamination",
    "Microplastic", "Nanoplastic", "Heavy_metal", "Radionuclide",
    "Pathogens", "Indicator_organism", "E_coli", "Fecal_coliform",
    "Soil_quality", "Soil_degradation", "Soil_erosion", "Desertification",
    "Salinization_soil", "Acidification_soil", "Compaction", "Contamination_soil",
    "Persistent_organic_pollutant_soil", "Heavy_metal_soil",
    "Landfill", "Sanitary_landfill", "Leachate", "Liner", "Cap",
    "Bioremediation", "Phytoremediation", "Mycoremediation", "Electrokinetics",
    "Soil_vapor_extraction", "Air_sparging", "In_situ_oxidation",
    "Waste_management", "Hazardous_waste", "Electronic_waste", "Radioactive_waste",
    "Medical_waste", "Waste_hierarchy", "Reduce_reuse_recycle",
    "Composting", "Anaerobic_digestion", "Waste_to_energy", "Incinerator",
    "Recycling", "Material_recovery_facility", "Contamination_recycling",
    "Energy_efficiency", "Energy_conservation", "Renewable_energy",
    "Solar_energy", "Wind_energy", "Hydroelectric_power", "Geothermal_energy",
    "Biomass_energy", "Biofuel", "Ethanol", "Biodiesel", "Biogas",
    "Green_building", "LEED_certification", "Energy_audit", "Weatherization",
    "Smart_grid", "Demand_response", "Peak_shaving", "Load_shifting",
    "Carbon_footprint", "Life_cycle_assessment", "Embodied_carbon",
    "Carbon_neutral", "Carbon_negative", "Carbon_offset", "Carbon_sequestration",
    "Nature_based_solutions", "Green_infrastructure", "Blue_infrastructure",
    "Wetland_restoration", "Forest_restoration", "Grassland_restoration",
    "Urban_greening", "Green_roof", "Green_wall", "Permeable_pavement",
    "Bioswale", "Rain_garden", "Constructed_wetland", "Phytoremediation_wetland",

    # Additional Technology & AI (300+)
    "Federated_learning", "Differential_privacy", "Homomorphic_encryption",
    "Secure_multi_party_computation", "Trusted_execution_environment",
    "Hardware_security_module", "Secure_enclave", "Intel_SGX", "ARM_TrustZone",
    "Zero_knowledge_proof", "Non_interactive_zero_knowledge", "zk_SNARK", "zk_STARK",
    "Commitment_scheme", "Merkle_tree", "Sparse_Merkle_tree", "Patricia_tree",
    "Trie_data_structure", "Suffix_tree_algorithm", "BWT_algorithm",
    "Stream_processing", "Apache_Kafka", "Apache_Spark_Streaming", "Flink_streaming",
    "Event_sourcing", "CQRS_pattern", "Saga_pattern", "Bulkhead_pattern",
    "Circuit_breaker", "Retry_logic", "Timeout_handling", "Rate_limiting",
    "Token_bucket", "Leaky_bucket", "Sliding_window", "Consistent_hashing",
    "Rendezvous_hashing", "Jump_hash", "Maglev_hashing", "Locality_sensitive_hashing",
    "MinHash", "SimHash", "Bloom_filter_advanced", "Counting_Bloom_filter",
    "Cuckoo_filter", "XOR_filter", "Quotient_filter", "GQ_filter",
    "Probabilistic_data_structure", "HyperLogLog", "T_digest", "Count_min_sketch",
    "Frequency_sketch", "Space_saving_algorithm", "Heavy_hitter_problem",
    "Approximate_nearest_neighbor", "LSH_forest", "Navigable_small_world",
    "Hierarchical_navigable_small_world", "HNSW", "Annoy", "Faiss",
    "Vector_database", "Milvus", "Weaviate", "Pinecone", "Qdrant",
    "Graph_database_advanced", "Neo4j", "ArangoDB", "JanusGraph", "TigerGraph",
    "RDF_database", "SPARQL", "Knowledge_graph", "Ontology_engineering",
    "Semantic_web", "Linked_data", "JSON_LD", "Microdata", "RDFa",
    "Search_engine", "Elasticsearch_advanced", "Solr", "Meilisearch", "Typesense",
    "Information_retrieval", "BM25", "TF_IDF", "Vector_search", "Hybrid_search",
    "Dense_retrieval", "Sparse_retrieval", "Colbert", "Dense_passage_retrieval",
    "Cross_encoder", "Re_ranking", "Learning_to_rank", "LambdaMART",
    "RankNet", "LambdaRank", "Pairwise_loss", "Listwise_loss",
    "Query_expansion", "Query_understanding", "Entity_linking", "Coreference_resolution",
    "Named_entity_recognition", "NER_advanced", "Sequence_labeling", "Tagging",
    "POS_tagging", "Chunking", "Dependency_parsing", "Constituency_parsing",
    "Semantic_parsing", "Relation_extraction", "Event_extraction", "Slot_filling",
    "Intent_detection", "Dialogue_state_tracking", "Conversational_AI", "Chatbot",
    "Task_oriented_dialogue", "Open_domain_dialogue", "Question_answering",
    "Extractive_QA", "Generative_QA", "Visual_question_answering", "VQA",
    "Image_captioning", "Visual_grounding", "Referring_expression_comprehension",
    "Object_detection", "YOLO", "Faster_RCNN", "Mask_RCNN", "EfficientDet",
    "RetinaNet", "FCOS", "CenterNet", "CornerNet", "Instance_segmentation",
    "Panoptic_segmentation", "Semantic_segmentation", "Pose_estimation",
    "Human_pose_estimation", "Hand_pose_estimation", "Face_detection", "Face_recognition",
    "Face_alignment", "Face_attribute", "Gait_recognition", "Person_re_identification",
    "Action_recognition", "Video_classification", "Video_understanding",
    "Temporal_action_localization", "Action_detection", "Spatio_temporal_learning",
    "3D_object_detection", "Point_cloud_processing", "PointNet", "PointNet++",
    "Voxel_based_methods", "Mesh_based_methods", "3D_reconstruction", "Photogrammetry",
    "Structure_from_motion", "SLAM", "Visual_odometry", "Optical_flow",
    "Scene_flow", "Stereo_vision", "Depth_estimation", "Monocular_depth",
    "Stereo_matching", "Disparity_estimation", "3D_scene_understanding",
    "Semantic_3D", "Instance_3D", "Panoptic_3D", "Indoor_scene_understanding",
    "Outdoor_scene_understanding", "Autonomous_driving", "Autonomous_vehicles",
    "Perception_for_autonomous_driving", "Planning_autonomous_driving",
    "Control_autonomous_driving", "CARLA_simulator", "Waymo_dataset",
    "Robotics_advanced", "Robot_vision", "Robot_manipulation", "Grasping",
    "Pick_and_place", "Motion_planning", "Path_planning", "Trajectory_planning",
    "Inverse_kinematics", "Forward_kinematics", "Dynamics_simulation", "Physics_engine",
    "Soft_robotics", "Exoskeletons", "Humanoid_robots", "Swarm_robotics",
    "Multi_robot_coordination", "Cooperative_control", "Distributed_control",
    "Reinforcement_learning_advanced", "Policy_gradient", "Actor_critic",
    "A3C", "PPO", "TRPO", "DDPG", "TD3", "SAC",
    "Q_learning", "DQN", "Double_DQN", "Dueling_DQN", "Rainbow_DQN",
    "Imitation_learning", "Behavior_cloning", "GAIL", "Inverse_reinforcement_learning",
    "Multi_task_learning", "Meta_learning", "Few_shot_learning", "Zero_shot_learning",
    "One_shot_learning", "Continual_learning", "Lifelong_learning", "Online_learning",
    "Active_learning", "Self_supervised_learning", "Contrastive_learning",
    "SimCLR", "MoCo", "BYOL", "SwAV", "Masked_language_modeling",
    "Causal_inference", "Causal_discovery", "Causal_representation_learning",
    "Counterfactual_explanation", "Fairness_in_ML", "Bias_detection", "Bias_mitigation",
    "Algorithmic_fairness", "Transparency_in_ML", "Interpretability", "Explainability",
    "LIME", "SHAP", "Attention_visualization", "Saliency_maps", "Grad_CAM",
    "Adversarial_examples", "Adversarial_training", "Robustness", "Certified_robustness",
    "Adversarial_attacks", "FGSM", "PGD", "C_W_attack", "DeepFool",
    "Backdoor_attacks", "Poisoning_attacks", "Model_stealing", "Membership_inference",
    "Privacy_attacks", "Differential_privacy_advanced", "Federated_learning_advanced",
    "Split_learning", "Vertical_federated_learning", "Horizontal_federated_learning",
    "Federated_averaging", "FedProx", "FedOptim", "Personalized_federated_learning",
    
    # Advanced Programming & Systems (250+)
    "Operating_system", "Linux", "Windows", "MacOS", "Unix", "POSIX",
    "Process_management", "Thread", "Context_switching", "Scheduling",
    "Memory_management", "Virtual_memory", "Paging", "Segmentation",
    "Garbage_collection", "Mark_sweep", "Generational_GC", "Concurrent_GC",
    "Parallel_GC", "Real_time_GC", "Cache_management", "Cache_coherence",
    "Cache_invalidation", "TLB", "Page_fault", "Thrashing",
    "File_system", "Inode", "FAT", "NTFS", "ext4", "BTRFS", "ZFS",
    "Filesystem_optimization", "Journaling", "Copy_on_write", "Snapshots",
    "RAID", "RAID0", "RAID1", "RAID5", "RAID6", "RAID10",
    "Network_protocol", "TCP_advanced", "UDP_advanced", "SCTP", "QUIC",
    "IP_protocol", "IPv4", "IPv6", "Multicast", "Anycast", "Broadcast",
    "Routing_protocol", "BGP", "OSPF", "RIP", "EIGRP", "ISIS",
    "DNS_advanced", "Domain_name_system", "DNS_resolution", "DNS_caching",
    "DNS_security", "DNSSEC", "DNS_over_HTTPS", "DNS_over_TLS",
    "Load_balancing_advanced", "Round_robin", "Least_connections", "IP_hash",
    "Weighted_load_balancing", "Sticky_sessions", "Health_checking",
    "Network_monitoring", "Packet_capture", "Tcpdump", "Wireshark", "Netflow",
    "Logging_systems", "Syslog", "ELK_stack", "Splunk", "Graylog",
    "Metrics_collection", "Prometheus", "Graphite", "InfluxDB", "OpenTSDB",
    "Distributed_tracing", "Jaeger", "Zipkin", "Datadog", "New_Relic",
    "APM", "Application_performance_monitoring", "Profiling", "Flamegraph",
    "Benchmarking", "Load_testing", "Stress_testing", "Chaos_engineering",
    "Chaos_monkey", "Gremlin", "Resilience_testing", "Disaster_recovery",
    "Business_continuity", "RTO", "RPO", "Backup_strategy", "Replication_strategy",
    "Deployment_strategy", "Blue_green_deployment", "Canary_deployment",
    "Rolling_deployment", "Feature_flag", "Dark_launch", "Rollback",
    "Infrastructure_as_code", "Terraform", "Ansible", "Chef", "Puppet",
    "Configuration_management", "Version_control", "Git_advanced", "Mercurial",
    "Perforce", "SVN", "Branching_strategy", "Git_flow", "GitHub_flow",
    "Pull_request", "Code_review", "Diff_algorithm", "Patch_management",
    "Container_orchestration", "Docker_advanced", "Kubernetes_advanced", "OpenShift",
    "Nomad", "Swarm_mode", "Pod", "Service", "Deployment", "StatefulSet",
    "DaemonSet", "Job", "CronJob", "Helm", "Kustomize", "Istio",
    "Service_mesh", "Envoy", "Linkerd", "Consul", "mTLS", "Circuit_breaking_mesh",
    "API_gateway", "Kong", "Nginx_plus", "AWS_API_Gateway", "Azure_API_Management",
    "Message_queue", "RabbitMQ", "ActiveMQ", "Apache_MQ", "NATS", "AWS_SQS",
    "Pub_sub", "Publisher_subscriber", "Topic", "Queue", "Dead_letter_queue",
    "Message_ordering", "Exactly_once_semantics", "At_least_once_semantics",
    "At_most_once_semantics", "Exactly_once_processing", "Idempotence",
    "Transaction_log", "Write_ahead_log", "Command_log", "Event_log",
    "Change_data_capture", "CDC", "Binlog", "WAL", "Redo_log",
    "Checkpointing", "Savepoint", "Recovery_mechanism", "Fault_tolerance",
    "Consensus_protocol", "Paxos_advanced", "Raft_advanced", "Zookeeper",
    "Etcd", "Consul_advanced", "Multi_Paxos", "Raft_optimization",
    "Byzantine_fault_tolerant", "BFT", "PBFT", "SBFT", "Tendermint",
    "Blockchain_consensus", "Proof_of_work", "Proof_of_stake", "Delegated_POS",
    "Proof_of_authority", "Proof_of_history", "Hybrid_consensus",
    "Smart_contract", "Solidity", "Vyper", "Rust_blockchain", "Move",
    "EVM", "Ethereum_virtual_machine", "WASM", "WebAssembly",
    "DeFi", "Decentralized_finance", "AMM", "Automated_market_maker",
    "Liquidity_pool", "Yield_farming", "Staking", "Governance_token",
    "DAO", "Decentralized_autonomous_organization", "NFT", "ERC721", "ERC1155",
    
    # Physics (300+)
    "Classical_mechanics", "Newtonian_mechanics", "Lagrangian_mechanics",
    "Hamiltonian_mechanics", "Action_principle", "Principle_of_least_action",
    "Noether_theorem", "Conservation_law", "Momentum_conservation",
    "Angular_momentum_conservation", "Energy_conservation", "Rotation",
    "Angular_velocity", "Angular_acceleration", "Moment_of_inertia", "Torque",
    "Precession", "Nutation", "Gyroscope", "Pendulum", "Harmonic_oscillator",
    "Damped_oscillation", "Forced_oscillation", "Resonance", "Q_factor",
    "Waves", "Wave_equation", "Wave_motion", "Frequency", "Wavelength",
    "Phase_velocity", "Group_velocity", "Dispersion", "Refraction", "Diffraction",
    "Interference", "Constructive_interference", "Destructive_interference",
    "Doppler_effect", "Shock_wave", "Sonic_boom", "Mach_number",
    "Sound_wave", "Acoustic_impedance", "Acoustic_resonance", "Reverberation",
    "Fluid_dynamics", "Navier_Stokes_equation", "Bernoulli_equation",
    "Continuity_equation", "Reynolds_number", "Turbulence", "Laminar_flow",
    "Boundary_layer", "Drag_force", "Lift_force", "Magnus_effect",
    "Vortex", "Eddy", "Cavitation", "Flow_separation", "Stagnation_point",
    "Thermodynamics_advanced", "First_law", "Second_law", "Third_law",
    "Zeroth_law", "Entropy", "Enthalpy", "Gibbs_free_energy", "Helmholtz_free_energy",
    "Chemical_potential", "Phase_transition", "Critical_point", "Triple_point",
    "Equation_of_state", "Van_der_Waals", "Virial_expansion", "Statistical_mechanics",
    "Boltzmann_distribution", "Partition_function", "Microstate", "Macrostate",
    "Ensemble", "Canonical_ensemble", "Grand_canonical_ensemble", "Microcanonical_ensemble",
    "Temperature", "Absolute_zero", "Heat_capacity", "Specific_heat", "Latent_heat",
    "Thermal_expansion", "Thermal_conductivity", "Thermal_diffusivity", "Seebeck_effect",
    "Peltier_effect", "Thermoelectric_effect", "Joule_heating", "Heat_transfer",
    "Conduction", "Convection", "Radiation", "Stefan_Boltzmann_law", "Planck_law",
    "Wien_displacement_law", "Rayleigh_Jeans_law", "Black_body_radiation",
    "Electromagnetism", "Electric_field", "Electric_potential", "Voltage",
    "Current", "Resistance", "Ohm_law", "Kirchhoff_law", "Joule_law",
    "Coulomb_law", "Gauss_law", "Electric_flux", "Faraday_law", "Lenz_law",
    "Ampere_law", "Maxwell_equation", "Electromagnetic_wave", "Poynting_vector",
    "Magnetic_field", "Magnetic_flux", "Magnetic_permeability", "Magnetic_susceptibility",
    "Ferromagnetism", "Paramagnetism", "Diamagnetism", "Antiferromagnetism",
    "Ferrimagnetism", "Hysteresis", "Curie_temperature", "Magnetic_domain",
    "Magnetization", "Magnetic_moment", "Spin", "Orbital_angular_momentum",
    "Precession_magnetic", "Nuclear_magnetic_resonance", "Electron_spin_resonance",
    "Lorentz_force", "Hall_effect", "Quantum_Hall_effect", "Fractional_quantum_hall",
    "Landau_level", "Cyclotron_motion", "Synchrotron_radiation", "Bremsstrahlung",
    "Cerenkov_radiation", "Transition_radiation", "Compton_scattering",
    "Pair_production", "Photoelectric_effect", "Photoemission", "X_ray_generation",
    "Bremsstrahlung_radiation", "Characteristic_X_ray", "Auger_effect",
    "Optics_advanced", "Ray_optics", "Geometrical_optics", "Lens_formula",
    "Aberration", "Chromatic_aberration", "Spherical_aberration", "Coma",
    "Astigmatism", "Field_curvature", "Distortion", "Vignetting",
    "Wave_optics", "Huygens_principle", "Fraunhofer_diffraction", "Fresnel_diffraction",
    "Double_slit_experiment", "Single_slit_diffraction", "Diffraction_grating",
    "Polarization", "Linear_polarization", "Circular_polarization", "Elliptical_polarization",
    "Brewster_angle", "Malus_law", "Jones_vector", "Mueller_matrix",
    "Birefringence", "Optical_activity", "Faraday_rotation", "Kerr_effect",
    "Pockels_effect", "Stark_effect", "Zeeman_effect", "Paschen_Back_effect",
    "Stark_Zeeman_effect", "Hyperfine_structure", "Fine_structure",
    "Quantum_mechanics_advanced", "Wave_function", "Schrodinger_equation",
    "Hamiltonian_operator", "Expectation_value", "Uncertainty_principle",
    "Commutator", "Anticommutator", "Hermitian_operator", "Observable",
    "Eigenvalue", "Eigenstate", "Superposition", "Entanglement", "Bell_state",
    "Quantum_teleportation", "Quantum_cryptography", "Quantum_key_distribution",
    "BB84", "E91", "Quantum_computing_advanced", "Qubit", "Quantum_gate",
    "Controlled_NOT", "Hadamard_gate", "Pauli_gate", "Phase_gate",
    "CNOT", "CCNOT", "Toffoli", "Fredkin", "Quantum_circuit",
    "Quantum_algorithm_advanced", "Phase_estimation", "Order_finding",
    "Hidden_subgroup", "Simon_algorithm", "Deutsch_algorithm", "Deutsch_Jozsa",
    "Bernstein_Vazirani", "Grover_algorithm", "Shor_algorithm_advanced",
    "Variational_quantum_algorithm", "QAOA", "VQE", "Quantum_simulation",
    "Quantum_error_correction_advanced", "Stabilizer_code", "Surface_code",
    "Topological_code", "Concatenated_code", "QECC", "Logical_qubit",
    "Quantum_annealing", "Adiabatic_quantum_computation", "D_Wave",
    "Nuclear_physics", "Nucleon", "Binding_energy", "Semi_empirical_mass_formula",
    "Nuclear_force", "Strong_force", "Nuclear_decay", "Alpha_decay", "Beta_decay",
    "Gamma_decay", "Radioactivity", "Half_life", "Activity", "Specific_activity",
    "Fission", "Fusion", "Nuclear_reaction", "Cross_section", "Activation_analysis",
    "Neutron_activation", "Reactor_physics", "Critical_mass", "Neutron_multiplication",
    "Chain_reaction", "Moderator", "Control_rod", "Coolant", "Reactor_core",
    "Particle_physics", "Standard_model", "Lepton", "Quark", "Gauge_boson",
    "Higgs_boson", "Fundamental_force", "Strong_interaction", "Electroweak_interaction",
    "Weak_interaction", "Gravity", "Graviton", "Supersymmetry", "SUSY",
    "Grand_unified_theory", "GUT", "Leptoquark", "Proton_decay", "Neutrino",
    "Neutrino_oscillation", "Neutrino_mass", "CP_violation", "Matter_antimatter",
    "Antimatter", "Positron", "Antiproton", "Antineutron", "Positronium",
    "Muon", "Tau", "Electron_neutrino", "Muon_neutrino", "Tau_neutrino",
    "Up_quark", "Down_quark", "Charm_quark", "Strange_quark", "Top_quark",
    "Bottom_quark", "Gluon", "Photon", "W_boson", "Z_boson",
    "Quantum_chromodynamics", "QCD", "Color_charge", "Confinement", "Asymptotic_freedom",
    "Hadron", "Meson", "Baryon", "Nucleon", "Pion", "Kaon", "Hyperon",
    "Quark_confinement", "Running_coupling", "QCD_scale", "Strong_coupling_constant",
    "Relativistic_quantum_mechanics", "Dirac_equation", "Klein_paradox",
    "Negative_energy_solution", "Dirac_sea", "Hole_theory", "Positron_prediction",
    "Relativistic_wave_equation", "Klein_Gordon_equation", "Weyl_equation",
    "Majorana_equation", "Spinor", "Spinor_field", "Spinor_connection",
    "Cosmology_advanced", "Friedmann_equation", "Hubble_constant", "Hubble_tension",
    "Scale_factor", "Redshift", "Luminosity_distance", "Comoving_distance",
    "Cosmic_microwave_background", "CMB", "Recombination", "Decoupling",
    "Baryons_acoustic_oscillation", "BAO", "Power_spectrum", "Correlation_function",
    "Inflation", "Inflationary_epoch", "Slow_roll_inflation", "Chaotic_inflation",
    "New_inflation", "Hybrid_inflation", "Inflaton", "Potential", "Slow_roll_parameter",
    "Primordial_gravitational_wave", "Tensor_mode", "Scalar_mode", "Gravitational_wave_detection",
    "LIGO", "Virgo", "LISA", "Pulsar_timing_array", "Stochastic_background",
    "General_relativity_advanced", "Metric_tensor", "Christoffel_symbol", "Riemann_curvature",
    "Ricci_curvature", "Ricci_scalar", "Einstein_tensor", "Stress_energy_tensor",
    "Einstein_field_equation", "Schwarzschild_metric", "Kerr_metric", "Reissner_Nordstrom",
    "Friedmann_Robertson_Walker", "FRW_metric", "FLRW_metric", "Geodesic", "Geodesic_deviation",
    "Gravitational_lensing", "Strong_lensing", "Weak_lensing", "Microlensing",
    "Gravitational_redshift", "Time_dilation", "Gravitational_time_dilation",
    "Schwarzschild_radius", "Event_horizon", "Singularity", "Naked_singularity",
    "Kerr_singularity", "Ring_singularity", "Cauchy_horizon", "Ergosphere",
    "Hawking_radiation", "Black_hole_thermodynamics", "Black_hole_entropy",
    "Bekenstein_bound", "Holographic_principle", "AdS_CFT_correspondence",
    "Wormhole", "Einstein_Rosen_bridge", "Traversable_wormhole", "Closed_timelike_curve",
    "Causal_paradox", "Grandfather_paradox", "Novikov_self_consistency",
    "Quantum_gravity", "Loop_quantum_gravity", "Spin_foam", "Spin_network",
    "String_theory", "Superstring", "M_theory", "Branes", "Calabi_Yau",
    "Moduli_space", "Compactification", "String_landscape", "Supersymmetry_string",
    "Heterotic_string", "Type_II_string", "Type_I_string", "Bosonic_string",
    "String_duality", "S_duality", "T_duality", "Mirror_symmetry", "Maldacena_duality",
    "Plasma_physics", "Plasma_state", "Ionization", "Debye_length", "Plasma_frequency",
    "Magnetohydrodynamics", "MHD", "Alfven_wave", "Magnetosonic_wave",
    "Plasma_instability", "Rayleigh_Taylor_instability", "Kelvin_Helmholtz_instability",
    "Weibel_instability", "Filamentation_instability", "Plasma_oscillation",
    "Cyclotron_frequency", "Drift_velocity", "Guiding_center", "Adiabatic_invariant",
    "Plasma_confinement", "Tokamak", "Stellarator", "Inertial_confinement",
    "Laser_plasma_interaction", "Stimulated_Raman_scattering", "Stimulated_Brillouin",
    "Laser_ablation", "Resonance_absorption", "Parametric_instability",
    
    # Chemistry (300+)
    "Organic_chemistry", "Aliphatic_compound", "Aromatic_compound", "Alicyclic",
    "Hydrocarbon", "Alkane", "Alkene", "Alkyne", "Diene", "Polyene",
    "Alkyl_group", "Aryl_group", "Acyl_group", "Alkoxy_group", "Ester",
    "Carboxylic_acid", "Carbonyl", "Aldehyde", "Ketone", "Carboxylic_acid_derivative",
    "Acyl_halide", "Acid_anhydride", "Carboxylic_acid_salt", "Amide", "Amine",
    "Imine", "Enamine", "Nitrile", "Isocyanate", "Thiocyanate", "Alcohol", "Phenol",
    "Ether", "Thiol", "Sulfide", "Disulfide", "Sulfoxide", "Sulfone", "Epoxide",
    "Oxirane", "Aziridine", "Diaziridine", "Organic_halide", "Alkyl_halide",
    "Aryl_halide", "Vinyl_halide", "Acyl_halide_compound", "Grignard_reagent",
    "Organolithium", "Organomagnesium", "Organocuprate", "Organoborane",
    "Organosilane", "Organozinc", "Organopalladium", "Organotitanium",
    "Carbene", "Nitrene", "Radical", "Carbanion", "Carbocation", "Enolate",
    "Ylide", "Zwitterion", "Mesoionic_compound", "Betaine", "Zwitter",
    "Stereochemistry", "Chirality", "Enantiomer", "Diastereomer", "Meso_compound",
    "Optical_isomerism", "Geometric_isomerism", "Cis_trans_isomerism",
    "E_Z_nomenclature", "R_S_nomenclature", "Absolute_configuration", "Fischer_projection",
    "Haworth_projection", "Wedge_dash", "Newman_projection", "Sawhorse_projection",
    "Conformer", "Rotamer", "Conformation", "Staggered", "Eclipsed", "Gauche",
    "Anti_conformation", "Chair_conformation", "Boat_conformation", "Twist_conformation",
    "Axial_position", "Equatorial_position", "Anomeric_carbon", "Alpha_beta_anomers",
    "Carbohydrate", "Monosaccharide", "Disaccharide", "Polysaccharide",
    "Glucose", "Fructose", "Galactose", "Ribose", "Deoxyribose", "Aldose", "Ketose",
    "Pentose", "Hexose", "Heptose", "Sugar_alcohol", "Glycoside", "Glycosidic_bond",
    "Starch", "Glycogen", "Cellulose", "Chitin", "Heparin", "Hyaluronic_acid",
    "Lipid", "Fat", "Oil", "Triglyceride", "Phospholipid", "Phosphatidylcholine",
    "Phosphatidylethanolamine", "Phosphatidylserine", "Phosphatidylinositol",
    "Cardiolipin", "Plasmalogen", "Glycolipid", "Cerebroside", "Ganglioside",
    "Sphingolipid", "Sphingosine", "Ceramide", "Sphingomyelin", "Wax", "Cholesterol",
    "Cholesterol_ester", "Steroid", "Sterol", "Terpene", "Monoterpene", "Sesquiterpene",
    "Diterpene", "Triterpene", "Polyterpene", "Carotenoid", "Xanthophyll",
    "Tocopherol", "Vitamin_A", "Vitamin_E", "Vitamin_D", "Vitamin_K",
    "Protein_advanced", "Amino_acid_chemistry", "Peptide_bond", "Polypeptide",
    "Primary_structure", "Secondary_structure", "Tertiary_structure", "Quaternary_structure",
    "Alpha_helix", "Beta_sheet", "Beta_turn", "Random_coil", "Intrinsically_disordered",
    "Disulfide_bond", "Salt_bridge", "Hydrogen_bond_protein", "Hydrophobic_interaction",
    "Van_der_Waals_interaction_protein", "Protein_folding_advanced", "Protein_misfolding",
    "Aggregation", "Amyloid", "Prion", "Protein_engineering", "Directed_evolution",
    "Computational_chemistry", "Quantum_chemistry", "Ab_initio", "Hartree_Fock",
    "Configuration_interaction", "Coupled_cluster", "Multi_configuration_methods",
    "Density_functional_theory", "DFT_advanced", "Exchange_correlation_functional",
    "LDA", "GGA", "Meta_GGA", "Hybrid_functional", "Range_separated_hybrid",
    "Molecular_orbital_theory", "LCAO", "Basis_set", "Gaussian_basis", "Slater_basis",
    "Plane_wave_basis", "All_electron_basis", "Pseudopotential", "Effective_core_potential",
    "SCF", "Self_consistent_field", "Hartree_Fock_method", "DFT_calculation",
    "Molecular_dynamics", "MD_simulation", "Force_field", "AMBER", "CHARMM", "GROMOS",
    "OPLS", "UFF", "MMFF94", "Lennard_Jones_potential", "Coulomb_interaction",
    "Ewald_summation", "Particle_mesh_Ewald", "Cutoff", "Neighbor_list",
    "Verlet_algorithm", "Leapfrog_integration", "Velocity_Verlet", "Rattle_algorithm",
    "Nose_Hoover_thermostat", "Berendsen_thermostat", "Langevin_dynamics",
    "Barostat", "Parrinello_Rahman", "Nose_Hoover_barostat",
    "Monte_Carlo_chemistry", "Monte_Carlo_simulation", "Importance_sampling",
    "Metropolis_algorithm", "Gibbs_ensemble", "Grand_canonical_ensemble_MC",
    "Transition_matrix_MC", "Umbrella_sampling", "Umbrella_sampling_advanced",
    "Histogram_reweighting", "Multicanonical_ensemble", "Wang_Landau_algorithm",
    "Molecular_mechanics", "Valence_angle", "Torsion_angle", "Out_of_plane_angle",
    "Van_der_Waals_parameter", "Partial_charge", "Atomic_partial_charge",
    "Point_charge", "Dipole", "Quadrupole", "Multipole_expansion",
    "Continuum_solvation", "Implicit_solvent", "Poisson_Boltzmann", "Generalized_Born",
    "Surface_area_based_solvation", "SASA", "Dielectric_constant", "Permittivity",
    "Analytical_chemistry", "Titration", "Acid_base_titration", "Redox_titration",
    "Precipitation_titration", "Complexometric_titration", "Gravimetric_analysis",
    "Coulometry", "Amperometry", "Potentiometry", "Voltammetry", "Cyclic_voltammetry",
    "Pulse_voltammetry", "Square_wave_voltammetry", "Electrochemistry_advanced",
    "Electrode", "Anode", "Cathode", "Electrochemical_cell", "Galvanic_cell",
    "Electrolytic_cell", "Half_cell", "Half_reaction", "Standard_electrode_potential",
    "Nernst_equation", "Electrochemical_series", "Overpotential", "Faradaic_current",
    "Non_faradaic_current", "Capacitive_current", "Charging_current",
    "Corrosion", "Oxidation_corrosion", "Galvanic_corrosion", "Crevice_corrosion",
    "Pitting_corrosion", "Intergranular_corrosion", "Stress_corrosion_cracking",
    "Passivation", "Protective_coating", "Cathodic_protection", "Sacrificial_anode",
    "Instrumental_analysis", "Spectroscopy", "UV_Vis_spectroscopy", "Infrared_spectroscopy",
    "Raman_spectroscopy", "Nuclear_magnetic_resonance", "NMR_advanced", "1H_NMR",
    "13C_NMR", "31P_NMR", "19F_NMR", "Two_dimensional_NMR", "COSY", "HSQC", "HMQC",
    "HMBC", "DEPT", "INEPT", "Decoupling", "NOE", "NOESY", "ROESY",
    "Spin_spin_coupling", "J_coupling", "Vicinal_coupling", "Geminal_coupling",
    "Long_range_coupling", "Coupling_constant", "Multiplet", "Splitting_pattern",
    "Doublet", "Triplet", "Quartet", "Quintet", "Sextet", "Septet",
    "Mass_spectrometry", "MS_advanced", "Electron_impact", "Chemical_ionization",
    "Electrospray_ionization", "ESI", "MALDI", "Atmospheric_pressure_ionization",
    "Ionization_source", "Mass_analyzer", "Quadrupole", "Time_of_flight", "TOF",
    "Magnetic_sector", "Fourier_transform_mass_spectrometry", "FTMS",
    "Orbitrap", "Ion_trap", "Penning_trap", "Paul_trap", "Fragmentation", "m_z_ratio",
    "Isotope_pattern", "Molecular_ion", "Base_peak", "Reconstruction_spectra",
    "Chromatography", "Gas_chromatography", "GC", "Liquid_chromatography", "LC",
    "HPLC", "Thin_layer_chromatography", "TLC", "Paper_chromatography",
    "Column_chromatography", "Flash_chromatography", "Size_exclusion_chromatography",
    "SEC", "Ion_exchange_chromatography", "Reverse_phase_chromatography",
    "Normal_phase_chromatography", "Chiral_chromatography", "Stationary_phase",
    "Mobile_phase", "Retention_time", "Selectivity", "Resolution", "Peak_tailing",
    "Electrokinetic_chromatography", "Electrophoresis", "Capillary_electrophoresis",
    "Gel_electrophoresis", "Isoelectric_focusing", "Isotachophoresis",
    
    # Additional specialized topics (2000+)
    # Earth Sciences
    "Seismology", "Earthquake", "Seismic_wave", "P_wave", "S_wave", "Surface_wave",
    "Rayleigh_wave", "Love_wave", "Seismograph", "Seismometer", "Richter_scale",
    "Moment_magnitude", "Mercalli_intensity", "Focal_mechanism", "Focal_depth",
    "Hypocenter", "Epicenter", "Fault", "Strike_slip_fault", "Normal_fault",
    "Reverse_fault", "Dip_slip_fault", "Transform_fault", "Subduction_zone",
    "Mid_ocean_ridge", "Hotspot", "Mantle_plume", "Volcanism", "Volcano",
    "Volcanic_eruption", "Effusive_eruption", "Explosive_eruption", "Pyroclastic_flow",
    "Lahars", "Volcanic_ash", "Tephra", "Pumice", "Lava", "Basalt", "Andesite",
    "Dacite", "Rhyolite", "Magma", "Magma_chamber", "Magmatic_system",
    "Crystallization", "Fractional_crystallization", "Partial_melting",
    "Geochemistry", "Trace_element", "Rare_earth_element", "REE", "Radiogenic_isotope",
    "Stable_isotope", "Isotope_ratio", "Fractionation", "Isotope_fractionation",
    "Geochemical_cycle", "Biogeochemical_cycle", "Sulfur_cycle", "Phosphorus_cycle",
    "Nitrogen_cycle", "Carbon_cycle", "Water_cycle", "Hydrological_cycle",
    "Weathering", "Chemical_weathering", "Physical_weathering", "Biological_weathering",
    "Soil_formation", "Pedogenesis", "Soil_horizon", "O_horizon", "A_horizon", "B_horizon",
    "C_horizon", "R_horizon", "Soil_type", "Mollisol", "Alfisol", "Spodosol",
    "Oxisol", "Inceptisol", "Vertisol", "Entisol", "Histosol", "Aridisol", "Ultisol",
    "Paleosol", "Archeosol", "Rock_type", "Igneous_rock", "Sedimentary_rock",
    "Metamorphic_rock", "Intrusive_rock", "Extrusive_rock", "Pluton", "Batholith",
    "Stock", "Sill", "Dike", "Laccolith", "Lopolith", "Phacolithe",
    "Clastic_rock", "Sandstone", "Shale", "Mudstone", "Siltstone", "Conglomerate",
    "Breccia", "Tillite", "Chemical_rock", "Rock_salt", "Evaporite", "Gypsum",
    "Limestone", "Dolomite", "Chert", "Flint", "Chalk", "Coal", "Organic_rock",
    "Peat", "Bituminous_coal", "Lignite", "Anthracite", "Petroleum", "Crude_oil",
    "Natural_gas", "Oil_shale", "Oil_sand", "Tar_sand", "Asphalt",
    "Metamorphism", "Regional_metamorphism", "Contact_metamorphism", "Cataclastic_metamorphism",
    "Retrograde_metamorphism", "Prograde_metamorphism", "Metamorphic_facies",
    "Zeolite_facies", "Prehnite_pumpellyite_facies", "Greenschist_facies",
    "Amphibolite_facies", "Granulite_facies", "Blueschist_facies", "Eclogite_facies",
    "Mineral", "Silicate_mineral", "Quartz", "Feldspar", "Olivine", "Pyroxene",
    "Amphibole", "Mica", "Clay_mineral", "Feldspathoidal", "Zeolite", "Carbonate_mineral",
    "Oxide_mineral", "Sulfide_mineral", "Phosphate_mineral", "Sulfate_mineral",
    "Halide_mineral", "Native_element", "Gemstone", "Diamond", "Corundum",
    "Beryl", "Topaz", "Tourmaline", "Garnet", "Jade", "Opal", "Turquoise",
    "Mineral_deposit", "Ore_deposit", "Ore_grade", "Ore_reserve", "Mining",
    "Strip_mining", "Underground_mining", "Open_pit_mining", "Solution_mining",
    "Placer_mining", "Processing", "Beneficiation", "Smelting", "Refining",
]




def clean_text(raw):
    lines = raw.splitlines()
    cleaned = []
    for line in lines:
        line = line.strip()
        if not line or len(line) < MIN_LINE_LEN:
            continue
        # Decode HTML entities first
        line = re.sub(r'&#\d+;', '', line)  # Remove numeric entities like &#93;
        line = re.sub(r'&[a-z]+;', '', line)  # Remove named entities like &nbsp;
        line = re.sub(r'&[#\w]*(?!;)', '', line)  # Remove incomplete entities
        
        special = sum(1 for c in line if not c.isalnum() and not c in ".,!?;:'-\n")
        if special > len(line) * 0.2:
            continue
        line = re.sub(r' +', ' ', line)
        line = re.sub(r'\[.*?\]', '', line)
        line = re.sub(r'\([^)]{40,}\)', '', line)
        line = line.strip()
        if len(line) < MIN_LINE_LEN:
            continue
        cleaned.append(line)
    return '\n'.join(cleaned)

def fetch_wikipedia(topic):
    url = f"https://en.wikipedia.org/wiki/{topic}"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' # this header (the line) is written by AI.
    }

    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        html = response.text
        # Extract main content between <p> tags
        content = re.findall(r'<p>(.*?)</p>', html, re.DOTALL)
        text = ' '.join(content)
        text = re.sub(r'<[^>]+>', '', text)
        return clean_text(text)
    except Exception as e:
        print(f"{topic} FAILED: {e}")
        return ""

def get_file_chars(path):
    if not os.path.exists(path):
        return 0
    with open(path) as p:
        return len(p.read())
        
def crawl():
    os.makedirs("data", exist_ok=True)
    if os.path.exists(OUTPUT_PATH):
        os.remove(OUTPUT_PATH)
        print("Cleared old corpus")

    print(f"TARGET: {TARGET_CHARS} chars")
    print(f"TOPICS: {len(TOPICS)}")
    
    total = 0
    done = 0
    for topic in TOPICS:
        if total >= TARGET_CHARS:
            break
        print(f"Fetching {topic}...")
        
        text =fetch_wikipedia(topic)
        if not text:
            print(f"{topic} had no content, skipping.")
            time.sleep(SLEEP_BETWEEN)
            continue
        with open(OUTPUT_PATH, "a") as f:
            for i in range(0, len(text), CHUNK_SIZE):
                f.write(text[i:i+CHUNK_SIZE] + "\n")
            f.write("\n")

        total += len(text)
        done += 1

        print(f" +{len(text):,} | Total: {total:,}")
        time.sleep(SLEEP_BETWEEN)

        
    print()
    print("=="*50)
    actual = get_file_chars(OUTPUT_PATH)
    print(f"Articles: {done}")
    print(f"Total chars: {actual:,}")
    print("Ready to train!" if actual >= TARGET_CHARS else "Not quite there, consider adding more topics.")

if __name__ == "__main__":
    crawl()

